### ISSUE TITLE
Forwarder toutes les URLs vers le index.html

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#1]
Actuellement, un refresh sur le site ne fonctionne pas (par exemple https://vitemado.se/33/plus75/rendez-vous), car les requêtes autres que celles sur `/` ne servent pas le `index.html`

**Comment by fcamblor** [comment]
Hello @nicolinuxfr, @rozierguillaume m'a dit que tu t'occupais du déploiement, c'est un reminder pour toi ;-)

**Comment by nicolinuxfr** [comment]
Yep, yep, yep, je pensais qu'on faisait un site statique, my bad. 

Fixed with https://github.com/CovidTrackerFr/covidtracker-server/commit/cadac9f4640fc3577c9ab1e0d0971371e0364925

Dites-moi s'il y a encore un souci.

**Comment by fcamblor** [comment]
C'est parfait merci 👏
