### ISSUE TITLE
Scroll automatique au focus sur le champ de recherche

### ISSUE THREAD

**Issue by bilelz** [CovidTrackerFr/vitemadose-front#114]
Hello,

![image](https://user-images.githubusercontent.com/1426314/115902904-3d2cdd00-a463-11eb-8e0f-466c768cba9a.png)

Pour avoir un affichage complet de la liste sous la barre de recherche, je propose d'appliquer un (smooth) scroll automatique au focus sur le champ de recherche

ça donnerait ça :
![image](https://user-images.githubusercontent.com/1426314/115903045-68173100-a463-11eb-929f-ab9bb504f7f1.png)

Cas d'usage testable ici : https://www.europcar.fr/fr-fr

Cdt.

**Comment by fcamblor** [comment]
Je ferme l'issue, la PR a été mergée 👌
