### ISSUE TITLE
Changer le wording "doses" => "créneaux"

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#116]
Il faudrait remplacer le wording ~doses~ et le remplacer par "créneaux"

**Comment by himanshu007-creator** [comment]
HI, je voudrais travailler sur cette question. Veuillez m'attribuer ceci. De plus, je voudrais demander, quels fichiers doivent être modifiés?

(j'ai utilisé le traducteur google pour ce commentaire🙂)

**Comment by PACMAN49** [comment]
Bonjour j'ai créer une branch pour corriger mais je n'ai pas les droits pour pousser cette branch surce repo. Comment faire?

**Comment by Luwangel** [comment]
Je pense qu'on peut fermer cette requête puisqu'elle a été corrigée : https://github.com/CovidTrackerFr/vitemadose-front/commit/d2c148ee397df7c235b968d9699d2a784335600e.

**Comment by Luwangel** [comment]
@PACMAN49 Pour contribuer à ce projet, il est nécessaire de passer par un clone en local.

En résumé :
1. Cloner le projet
2. Créer une nouvelle branche en local
3. Faire les correctifs sur cette branche locale
4. Pousser tes changements sur ton dépôt local
5. Ouvrir une PR sur le dépôt d'origine (Github te proposera de le faire via l'interface Web)

https://gist.github.com/MarcDiethelm/7303312

**Comment by fcamblor** [comment]
> Je pense qu'on peut fermer cette requête puisqu'elle a été corrigée : d2c148e.

En fait je la garde ouverte car j'aimerais faire quelques modifs de wording dans le code aussi (où il reste quelques endroits où on parle de doses au lieu de créneaux)

**Comment by PACMAN49** [comment]
je vais regarder si ma branche corrige toujours des choses, dans ce cas je
pousse un PR ce soir.

**Comment by fcamblor** [comment]
Je ferme, j'ai terminé le refacto sur le code à l'instant via 8b87318
