### ISSUE TITLE
Pas de page 404

### ISSUE THREAD

**Issue by nicolinuxfr** [CovidTrackerFr/vitemadose-front#12]
Les 404 sont vides, avec juste l'en-tête du site, il faudrait sans doute prévoir un message informatif au minimum, ou alors de rediriger systématiquement sur la page d'accueil ?

**Comment by fcamblor** [comment]
J'ai fait en sorte de rediriger sur la home sur une route inconnue.

**Comment by nicolinuxfr** [comment]
Google veut une vraie 404, donc au boulot ! 🙂

**Comment by fcamblor** [comment]
@francoisbouchet est chaud pour nous faire une 404.html avec des 🦄  et des 🌈  dedans ?

**Comment by fcamblor** [comment]
@alexandreGUY si tu es chaud pour faire une inté de 404 aussi n'hésites pas ! :)

**Comment by nicolinuxfr** [comment]
Et au choix, vous pouvez gérer la 404 de votre côté, ou alors je peux le faire côté serveur. Vous me dites ce qui vous arrange.

**Comment by alexandreGUY** [comment]
@fcamblor Y'a une maquette de la 404 ou c'est freestyle ? :)

**Comment by fcamblor** [comment]
@alexandreGUY si tu dégaines avant @francoisbouchet c'est freestyle (je te fais confiance ;-))

Si possible, essaie d'éviter le plus possible les assets externes (styles inline / embedded dans le html, data url pour les images, toussa)

**Comment by fcamblor** [comment]
> Et au choix, vous pouvez gérer la 404 de votre côté, ou alors je peux le faire côté serveur. Vous me dites ce qui vous arrange.

Je pense que Google parle de celle du serveur (parce que sinon, ils sont sacrément balèzes pour comprendre que le js fait une "redirection" à cause d'une page non trouvée par le routeur front, sachant qu'aucun HTTP 404 ne pop à aucun moment dans ce cas..)

**Comment by nicolinuxfr** [comment]
Ils sont assez forts pour analyser les sites JS alors je serais pas aussi affirmatif que toi.

Enfin pas de problème. Dans ce cas, je veux bien un fichier 404.html à la racine du site.

EDIT : c'est en place côté serveur, mais tant que la redirection vers la home sera en place, c'est elle qui aura la main. Comme ça c'est pas plus mal, vous pourrez coordonner la mise en production.

Sachant que ça marchera pareil sur les versions en développement.

**Comment by francoisBouchet** [comment]
proposition de page d'Erreur 404. O:-)

https://svelte.dev/repl/52bb73932e4242d79d632f9f94388897?version=3.38.1

**Comment by fcamblor** [comment]
Quel :trollface: celui-ci :P

**Comment by jblp56** [comment]
[quelques guidelines SEO de la part de Google
](https://developers.google.com/search/docs/advanced/crawling/custom-404-pages?hl=fr)

> Étant donné qu'une page d'erreur 404 peut également être une page HTML standard, vous pouvez la personnaliser à votre guise. Voici quelques suggestions pour créer une page d'erreur 404 efficace qui incite les visiteurs à rester sur votre site et les aide à trouver les informations qu'ils recherchent :
> 
> - Indiquez clairement aux internautes que la page qu'ils recherchent est introuvable. Adoptez un langage avenant et agréable.
> - Assurez-vous que votre page d'erreur 404 garde la même apparence graphique (navigation comprise) que le reste de votre site.
> - Pensez à ajouter des liens vers vos articles ou messages les plus consultés, ainsi que vers la page d'accueil de votre site.
> - Pensez à proposer aux internautes la possibilité de signaler les liens non fonctionnels.
> - Quels que soient l'attrait et l'utilité de votre page d'erreur 404 personnalisée, vous ne souhaitez probablement pas qu'elle s'affiche dans les résultats de recherche Google. Pour empêcher l'indexation des pages 404 par Google et par les autres moteurs de recherche, assurez-vous que votre serveur Web affiche un code d'état HTTP 404 lorsqu'une page manquante est demandée.
> - Utilisez l'outil de changement d'adresse pour indiquer à Google le déplacement de votre site.

**Comment by alexandreGUY** [comment]
@fcamblor J'ai ajouté une page 404.html dans le dossier src. Je ne suis pas certain que c'est là qu'elle doit aller, je te laisse prendre la suite ?  (Sur la branche 404-page : https://github.com/CovidTrackerFr/vitemadose-front/tree/404-page)

Screen de la page : 
![Screenshot 2021-05-05 at 23 23 24](https://user-images.githubusercontent.com/1073420/117211143-ed51fc80-adf8-11eb-9511-3531525878a5.png)
