### ISSUE TITLE
Intégrer l'infographie du gouvernement vis à vis de l'éligibilité

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#130]
Cf cette image :
![image](https://user-images.githubusercontent.com/603815/116486910-00ac1780-a88f-11eb-9e45-2bcf796c0d6f.png)
Source: https://www.gouvernement.fr/sites/default/files/cimages/infog_vaccins_particuliers.png

Ce n'est pas forcément fou au niveau accessibilité (mais en toute honnêteté je ne suis pas sûr que le reste du site soit ultra utilisable sur une liseuse pour personne déficiente visuelle) et ça présente l'avantage d'être très facile à maintenir/mettre à jour (récupération de la dernière version du fichier, voire référence "en direct" du fichier sur le site du gouvernement)

**Comment by FKSI** [comment]
Ce serait encore mieux si on pouvait avoir une pop-up en demande l'âge de la pers. a vacciner et que ça filtre les résultats en conséquence :)

**Comment by fcamblor** [comment]
@FKSI À maintenir, ça va être compliqué...

Quand je vois que ne serait-ce qu'avec 3 bouts de texte, on met une semaine pour s'aligner sur l'annonce du gouvernement ... alors si en plus on doit faire du dev pour s'aligner à des choses qui risquent de changer régulièrement dans les semaines qui viennent, je suis pas chaud pour m'embarquer là-dedans et préfère garder les choses simples, et simplement éditable par le commun des mortels.

**Comment by FKSI** [comment]
Make sense aussi ;).

**Comment by bilelz** [comment]
Hello, une version PDF existe https://solidarites-sante.gouv.fr/IMG/pdf/infog_vaccins_particuliers.pdf | https://github.com/CovidTrackerFr/vitemadose-front/pull/132#discussion_r623775687

**Comment by Noezor** [comment]
Il semblerait que ce [calculateur du gouvernement](https://www.gouvernement.fr/etes-vous-eligible-a-la-vaccination-contre-la-covid-19) soit mis à jour aussi.

**Comment by mccob** [comment]
> @FKSI À maintenir, ça va être compliqué...
> 
> Quand je vois que ne serait-ce qu'avec 3 bouts de texte, on met une semaine pour s'aligner sur l'annonce du gouvernement ... alors si en plus on doit faire du dev pour s'aligner à des choses qui risquent de changer régulièrement dans les semaines qui viennent, je suis pas chaud pour m'embarquer là-dedans et préfère garder les choses simples, et simplement éditable par le commun des mortels.

La vaccination en AZ ou J&J sera peut être ouverte un jour au moins de 55 ans en effet (et encore que l'UE ne renouvelle pas ses commandes donc on peut se poser la question https://www.lemonde.fr/international/article/2021/04/26/avec-sa-plainte-la-commission-europeenne-confirme-ne-plus-miser-sur-astrazeneca-a-l-avenir_6078151_3210.html ).

Il est bien évident qu'il est trop complexe de coder les conditions d'éligibilité, par contre depuis hier, les <55 ans avec comorbidité sont éligibles aux vaccins par ARN messager uniquement (donc pas AZ et pas J&J), du coup ça serait quand même bien (surtout en vu de l'ouverture à tous plus tard), de mettre une option du genre "type de vaccin : ARN messager / autre". Comme ça vous ne rentrez pas dans une mise en place complexe des conditions d'éligibilités et vous simplifiez les recherches pour les < 55 ans (surtout tant que AZ et J&J ne sont pas ouvert à tous).

**Comment by mccob** [comment]
J'ai fait une version avec le filtre par type de vaccin (j'ai pas l'habitude de travailler du Node donc je vous laisse vérifier le code si vous voulez l'intégrer : https://github.com/mccob/vitemadose-front mais il fonctionne en local ).

edit : j'ai réussi à faire un fork plus propre, j'ai donc mis à jour l'url au dessus, je peux donc faire une PR à présent si vous êtes OK pour proposer la fonctionnalité (et il restait un bug)

![image](https://user-images.githubusercontent.com/1292704/116815679-e8721c00-ab5e-11eb-9a45-638118713d7e.png)

**Comment by Noezor** [comment]
Hello @mccob et bienvenue ! Tu voudrais faire une PR ?

**Comment by mccob** [comment]
Voilà, j'ai fait un PR.

**Comment by FKSI** [comment]
J'aime beaucoup la feature pour choisir le type de vaccin mais je suis pas sûr que ça aille dans le sens du gouvernement car en permettant faire ce choix simplement on va inciter les gens à prendre du Pfizer au lieu de l'AZ, alors oui, on le fait peut-être  déjà de manière "implicite".

**Comment by mccob** [comment]
> J'aime beaucoup la feature pour choisir le type de vaccin mais je suis pas sûr que ça aille dans le sens du gouvernement car en permettant faire ce choix simplement on va inciter les gens à prendre du Pfizer au lieu de l'AZ, alors oui, on le fait peut-être déjà de manière "implicite".

à l'heure actuelle, seuls les plus de 55 ans sont éligibles aux vaccins à base d'adénovirus

une bonne partie des concernés a déjà été vaccinée ou va l'être dans les prochaines semaines : https://twitter.com/nicolasberrod/status/1388927135272800259 

il faudrait calculer par rapport à la pyramides des âges mais la plupart du potentiel des recherches qui vont être faites dans les prochaines semaines vont être faites par des 18-54 ans qui ne sont éligibles qu'en ARNm.

c'est pourquoi à mon sens cette fonctionnalité est nécessaire.

Et même si on estime qu'il est probable que les vaccins par adénovirus soient comme en Allemagne (à certains endroits à minima) autorisés pour tout les adultes https://www.lefigaro.fr/sciences/covid-19-veran-saisit-la-has-sur-la-possibilite-d-ouvrir-la-vaccination-astrazeneca-a-tous-les-volontaires-20210430 , on peut aussi respecter le choix des gens qui veulent de l'ARNm. 

Par ailleurs il y a aussi des raisons de vouloir privilégier l'ARNm, en Moselle (et d'autres départements pourraient être concernés aussi si le variant afsud s'y répands...), la DGS privilégie les vaccins par ARNm (et le Jansen qui commence à être déployé depuis peu sauf que malgré ce qu'écrit la DGS, sur vitemadose pas de centre proposé en Moselle avec Jansen ...) car il est clairement (c'est moins clair pour l'AZ) démontré qu'il sont efficaces contre certains variants (afsud) : https://solidarites-sante.gouv.fr/IMG/pdf/dgs-urgent_50_modalites_specifiques_moselle.pdf

**Comment by fcamblor** [comment]
@mccob tu voudrais pas aller ouvrir une issue "à coté" parce que là on a énormément dérivé du sujet de l'issue...

**Comment by Luwangel** [comment]
L'image et les règles ont changé et sont susceptibles de changer régulièrement (l'infographie change fréquemment d'URL).

Afin d'éviter de se retrouver avec une image qui ne pointe "sur rien", nous avons préféré ne pas l'intégrer.

Nous avons ajouté à la place un texte informatique qui redirige vers le site officiel du gouvernement.
