### ISSUE TITLE
Message de service 

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose-front#136]
Ajouter la possibilité de mettre un message de service, ou d’avertissement ´ (exemple : « Les RDV sur la plateforme xxx ne sont pas détectés en raison d’incidents techniques. »), qui s’affiche sur la page des résultats. 

À partir d’un JSON ou d’une remote config Firebase, par exemple.

**Comment by Aymerik** [comment]
Lié à l'issue #199 du coup ?

**Comment by fcamblor** [comment]
Je ferme car duplicata de #199 pour moi (et on a la pR #262 en cours pour gérer ça ;-) )
