### ISSUE TITLE
Windows 🤦‍♂️ : "git clone error" à cause du nom des fichiers aux.json et con.json

### ISSUE THREAD

**Issue by bilelz** [CovidTrackerFr/vitemadose-front#139]
Hello,

Sur Windows, les fichiers ne peuvent pas avoir `aux` ou `con` comme nom.
Du coup un `git clone` n'est pas possible : 
![image](https://user-images.githubusercontent.com/1426314/116813755-b01a1000-ab55-11eb-9eec-0eccc87e54ad.png)

Liste des noms interdits 🤦‍♂️ : https://answers.microsoft.com/en-us/windows/forum/windows_7-files/why-cant-i-create-a-folder-with-name/23c86662-4988-4c7d-9c2d-3e33d4413de3

Si possible, renommer
- [ ] aux.json > _aux.json
- [ ] con.json > _con.json

**Comment by fcamblor** [comment]
🤯

**Comment by fcamblor** [comment]
Je ferme car @Luwangel a fourni un fix que je viens de merger (merci) :-)
