### ISSUE TITLE
Améliorer la mise en forme du contenu "about"

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#15]
Plusieurs possibilités :

- Intégrer ce qu'a fait @alexandreGUY sur la branche `dev` (facilement dispo donc) :
![Screenshot 2021-04-09 at 10 37 37](https://user-images.githubusercontent.com/603815/114159814-7ecb6d00-9926-11eb-9457-348889f9b0b0.png)

- Intégrer la version 1 du Figma (nécessite un peu de rework de la part d' @alexandreGUY )
<img width="1440" alt="Desktop - 1" src="https://user-images.githubusercontent.com/603815/114159929-9efb2c00-9926-11eb-896a-c7e28c34fc56.png">

- Intégrer la version 3 du Figma (nécessite un peu de rework de la part d' @alexandreGUY )
<img width="1440" alt="Desktop - 3" src="https://user-images.githubusercontent.com/603815/114159935-a1f61c80-9926-11eb-9a95-efb8ea3a7201.png">

J'ai besoin d'une validation pour savoir sur quelle option partir.

PS: il faudra homogénéiser le choix de mise en forme sur la page Centre

**Comment by fcamblor** [comment]
On peut aussi faire en 2 étapes : rapide avec l'intégration de la solution d' @alexandreGUY 
Et dans un deuxième temps avec l'intégration d'un des 2 figma.

**Comment by francoisBouchet** [comment]
alors on en discutait en private avec Adrien, il m'a fait réduire ma typo, (j'ai mis du 22px) et réduire le line-height également ('jai mis à 160%) sur figma

**Comment by fcamblor** [comment]
_(pour rappel, le figma est [ici](https://www.figma.com/file/ISBVZxqhgxylKucAsldoe1/ViteMaDose?node-id=0%3A1)_

**Comment by rozierguillaume** [comment]
Je crois qu’Adrien bosse sur une version non ?

**Comment by adrochet** [comment]
Voici ma version 
<img width="1440" alt="Desktop - 1" src="https://user-images.githubusercontent.com/17876938/114166711-63646000-992e-11eb-8a63-9bb864c273ce.png">

**Comment by adrochet** [comment]
et je pense que ça serait bien que le "A propos" du header soit une ancre qui descend jusqu'à la FAQ

**Comment by francoisBouchet** [comment]
nickel ! merci Adrien :)

**Comment by fcamblor** [comment]
> et je pense que ça serait bien que le "A propos" du header soit une ancre qui descend jusqu'à la FAQ

L'équipe mobile aimerait bien avoir un moyen de linker sur une FAQ depuis l'appli mobile (cf #14).
Du coup, 3 options possibles :
- On déplace toute la FAQ sur une page dédiée :
  - Cette nouvelle page est linkée par le lien "A propos" en haut...
  - ...mais également par les applis mobile 
  - La FAQ n'apparaîtra donc plus sur la Home (par contre, elle apparaîtra dans le index.html pour l'indexation par les bots, pas de soucis sur ça)
- Comme tu le suggères, on ne créée pas de nouvelle page
  - Le lien "A propos" fait une ancre sur cette section
  - Les applis mobiles utilisent un lien avec l'ancre pour targetter cette section .. par contre, ça fera peut-être un peu bizarre à l'utilisateur d'arriver sur la home où un moteur de recherche similaire à ce qu'il a dans l'app est présent...
- Un Mix des deux : on laisse la section FAQ sur la Home, et on créée une nouvelle page avec juste le contenu de la FAQ.
  - Les infos ne seront pas dupliquées, je peux "référencer" le bloc de la FAQ indexée par les moteurs de recherche depuis à la fois la Home et la nouvelle page A propos
  - J'aurais tendance à encourager les applis mobile à ouvrir la page dédiée à la FAQ, pour éviter le point négatif évoqué dans l'option précédente

**Comment by francoisBouchet** [comment]
J'aime bien l'idée du mix, ça a l'inconvénient, je pense de créer du "Duplicate Content" chez Google, le mieux est d'indiquer à Google que cette FAQ-vmobile.html est une canonical de notre homepage : cf. [https://fr.semrush.com/blog/url-canonique-guide-2020-balises-canonical/ ](https://fr.semrush.com/blog/url-canonique-guide-2020-balises-canonical/ )

**Comment by fcamblor** [comment]
Je préfèrerais attendre de voir que Google considère vraiment ça comme du duplicated content, car c'est pas aussi simple selon moi :
- Tout ce qui n'est pas dans le index.html sera chargé dans le DOM via du JS (bon, on sait tous que Google sait maintenant indexer les portions générés via du JS... mais je sais pas si ça marche si bien que ça)
- Ce contenu est ajouté dans le "shadow DOM" de chaque composant. Je ne sais pas du tout si Google indexe les choses dans le shadow DOM (pas le temps de me renseigner là tout de suite, je verrai ptet ce week end), mais ça ne m'étonnerait pas qu'il ne le fasse pas (c'est la double peine : shadow DOM + alimentation via du JS).

C'est pour ces raisons que j'ai préféré me la jouer safe et mettre le plus de contenu important et indexable dans l'index.html... ce faisant, je limite le plus possible les surprises qu'on pourrait avoir :)

**Comment by rozierguillaume** [comment]
Niveau maintenabilité je me dis que c'est plus simple de ne pas dupliquer, non ?
Et perso ça ne me choque pas beaucoup si les users mobile sont redirigés vers une ancre de la hompeage.

**Comment by fcamblor** [comment]
La maintenabilité n'est pas un sujet pour moi (en tous cas sur les aspects "production de contenu") : le contenu sera présent à un et un seul endroit (dans le index.html, indexé par les bots, [ici](https://github.com/CovidTrackerFr/vitemadose-front/blob/main/index.html#L56))

C'est le but des `slot` : mettre un "bloc de HTML" à disposition des composants pour qu'ils puissent le manipuler comme bon leur semble (on peut l'afficher à plein d'endroits du site différent, voire ne pas les afficher du tout si besoin)

Après, si par maintenabilité tu pensais que "fournir" un même contenu sur un site à des endroits différents, pourrait représenter un soucis pour que les applications externes pointent "sur **\*le bon endroit\***, qui pourrait changer au fil du temps", alors oui ça pourrait être un sujet (mais je préfèrerais y être confronté plutôt que de trop l'anticiper pour rien)

**Comment by rozierguillaume** [comment]
Ok d'accord je vois
C'est comme vous voulez alors :)
