### ISSUE TITLE
[Doctolib] Partners URL vers Normal URL

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose-front#158]
Hello l'equipe front,

Nous avons une demande urgente de changer les URLs de Doctolib dites "partners" par exemple https://partners.doctolib.fr/centre-de-sante/vesoul/centre-de-vaccination-covid-19-de-vesoul?speciality_id=5494&enable_cookies_consent=1

Vers les URL de ce type - "https://www.doctolib.fr/" par exemple pour ce centre^^^:

https://doctolib.fr/centre-de-sante/vesoul/centre-de-vaccination-covid-19-de-vesoul?speciality_id=5494&enable_cookies_consent=1

Pour résumer Doctolib nous demande de remplacer `https://partners.` par `https://`.

Nous pensons que faire le changement sur le front semble etre le plus rapide jusqu'a un fix plus profond.

Nous pourrions le changer sur le backend mais cela va causé un autre probleme pour Santé.fr qui utilise nos donnée. Nous pourrions egalement rajouter un nom du champ mais cela semble peu efficace et va necessiter une reecriture du modele JSON.

**Comment by Maijin** [comment]
Bloqué par les applications:

```Oui, si c’est vraiment urgent on peut pas le changer tout de suite :confused:
Nouveaux messages

Faut faire le code change, tester et envoyer, en principe ça va vite mais il faudrait compter 12/24h pour iOS
```

**Comment by nhumblot** [comment]
@Maijin je prends le point et j'ouvre une PR ce soir.
