### ISSUE TITLE
Créer une page pour les doses "last minute"

### ISSUE THREAD

**Issue by cdugeai** [CovidTrackerFr/vitemadose-front#159]
Comme l'a présenté Emmanuel Macron dans [un tweet](https://twitter.com/EmmanuelMacron/status/1390250148526231553), "Aucun créneau ne doit être perdu." en parlant des doses "last minute" (rdv de vaccination non pourvu du jour pour le lendemain).

@rozierguillaume a [annoncé une adaptation](https://twitter.com/GuillaumeRozier/status/1390239205511606274) de *ViteMaDose* mais je n'ai pas réussi à trouver de trace de cette feature dans le code/issues/PR.

Y a t-il un suivi de cette feature que je n'ai pas vu ?

**Comment by fcamblor** [comment]
C'est ici : https://github.com/CovidTrackerFr/vitemadose-front/pull/155
