### ISSUE TITLE
Afficher l’heure de mise à jour en relatif ?

### ISSUE THREAD

**Issue by nicolinuxfr** [CovidTrackerFr/vitemadose-front#16]
C’est une suggestion. : je trouverais ça plus lisible d’avoir l’heure de mise à jour des donnés en relatif. Plutôt « il y a 5 minutes » que l’heure précise.

**Comment by rozierguillaume** [comment]
+1
ça devrait être possible avec `moment().fromNow()` en Javascript

**Comment by fcamblor** [comment]
Carrément ! Après, moment [est assez indigeste niveau taille de bundle](https://bundlephobia.com/result?p=moment@2.29.1) et [est annoncé comme déprécié](https://momentjs.com/docs/#/-project-status/) au profit de [Luxon](https://moment.github.io/luxon/) ([qui est 4 fois moins volumineux, mais reste sur 70kb tout de même](https://bundlephobia.com/result?p=luxon@1.26.0))

Je suis partagé entre le buy vs build : tant qu'on n'a que peu de calculs de dates, on peut se contenter de faire les choses à la main je pense (j'ai fait attention à centraliser tous ces calculs de dates au sein d'une classe utilitaire qu'on pourra jeter le jour où on "achètera" une lib pour faire les choses).

On est d'accord que l'ordre de grandeur des échelles de mise à jour ça va être un truc du type :
- Durée <=59min : "Il y a X minutes"
- Durée <=6h : "Il y a Xh et Y minutes"
- Durée <1j : "Il y a X heures"
- Durée <3j : "Il y a X jours et Y heures"
- Au-delà : "Il y a X jours"
