### ISSUE TITLE
Android Install Native app banner

### ISSUE THREAD

**Issue by michgauz** [CovidTrackerFr/vitemadose-front#160]
Hello!
Est ce qu'on peut regarder ce que ça donne ce genre d'implémentation ?

https://developers.google.com/web/fundamentals/app-install-banners/native

**Comment by fcamblor** [comment]
Yes, je vais sortir la partie PWA de la branche `push-notifs` pour intégrer le webmanifest de cette branche et intégrer ces éléments d'application native pour voir ce que ça donne ! 👍

**Comment by michgauz** [comment]
Thanks :)
