### ISSUE TITLE
Problèmes visuels sur les statistiques

### ISSUE THREAD

**Issue by aureliancnx** [CovidTrackerFr/vitemadose-front#169]
La page des stats souffre de quelques petits problèmes visuels sur mobile.

- Device : iPhone XS Max

Descriptif du problème : 

- Les labels du chart en Y sont collés (graph trop petit?)
- Nécessité de scroll à droite pour voir toute la card

![D4992BD3-8E32-498C-ADE5-64C42B79D5C0](https://user-images.githubusercontent.com/72009413/117541502-7a24d200-b014-11eb-8d3d-88f00bec0c82.png)

**Comment by Aymerik** [comment]
Le problème devrait être corrigé avec la PR #177

**Comment by Aymerik** [comment]
Hello @aureliancnx tu confirmes que le problème est bien réglé depuis cette adresse https://dev.vitemado.se/dev/ ?

**Comment by fcamblor** [comment]
Je ferme l'issue, @aureliancnx n'hésites pas à la reopen si tu vois que le soucis n'est pas réglé chez toi :)
