### ISSUE TITLE
`label` inactif

### ISSUE THREAD

**Issue by viki53** [CovidTrackerFr/vitemadose-front#170]
Dans le formulaire pour chercher une localisation, le `<label>` à gauche est inactif car non lié au champ de recherche.

Il faudrait définir un attribut `for` qui corresponde à l'attribut `id` du champ pour rendre le libellé du champ accessible aux lecteurs d'écrans, tout en augmentant la surface de la zone réactive (pratique par exemple sur mobile ou pour les personnes n'ayant pas une grande précision pour pointer).

**Attention** : l'`input` étant actuellement dans un Shadow-DOM, il n'est pas accessible directement par le `<label>`, il faudrait donc déplacer ce dernier dans le composant. [Une issue](https://github.com/whatwg/html/issues/3219) est ouverte à ce sujet par le WHATWG pour trouver une autre solution.

**Comment by bilelz** [comment]
Corrigé #176
