### ISSUE TITLE
Problème de responsive sur iOs 

### ISSUE THREAD

**Issue by lc-dx** [CovidTrackerFr/vitemadose-front#172]
Bonsoir, 
Les deux premiers graphs de la page des stats ne fit pas en mode portrait lorsque je consulte le site via mon iPhone(XS, iOS 14.4.2 sur safari). Tout semble fonctionner en paysage.
Si vous avez besoin de plus d'infos, n'hésitez pas à me faire signe.
![IMG_639620D6A4AB-1](https://user-images.githubusercontent.com/82411720/117551439-4b275400-b046-11eb-9d08-d9672139b060.jpeg)

**Comment by nicolasverlhiac** [comment]
Hello, ce problème me semble se retrouver sur tous les écrans lorsque le point de rupture est < 450px.

**Comment by nhumblot** [comment]
Salut @lc-dx :wave: 

Est-ce que tu peux confirmer que c'est ok pour toi sur https://dev.vitemado.se/dev/ ?

**Comment by fcamblor** [comment]
Je ferme l'issue, @lc-dx n'hésites pas à reopen si tu as toujours le soucis après les changements de #177
