### ISSUE TITLE
Faute de frappe paragraphe chronodose 

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose-front#174]
Bonjour,

Sur la home vitemadose.covidtracker.fr il y a une faute de frappe dans le paragraphe expliquant chronodose.

![IMG_20210509_105642.jpg](https://user-images.githubusercontent.com/82476476/117566195-8876fa80-b0b5-11eb-9b6e-c3381387bcd6.jpg)

Thanks 🙂

**Comment by nhumblot** [comment]
Merci pour le signalement, c'est désormais corrigé sur la branche `dev`. :+1:
