### ISSUE TITLE
Sémantique : remplacer toutes les occurences de "Centre" par "Lieu"

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#18]
Depuis qu'on peut vacciner en pharmacie / chez le généraliste, il vaut mieux être plus générique au niveau sémantique

**Comment by nhumblot** [comment]
Est-ce que le remplacement de ces occurences doit être effectué dans les libellés et le code, ou seulement un des deux périmètres est envisagé par ce ticket ?

**Comment by fcamblor** [comment]
J'aurais dit les deux mon colonel !

Si tu prends le sujet, je pense qu'il faut bien prévenir car ça va être un nid à conflits :) (c'est aussi pour ça que le plus tôt on le fait et le mieux c'est !)

(✋ Nico :-))

**Comment by fcamblor** [comment]
Techniquement, les changements sémantiques ont été appliqués via #22

Il reste à voir si on souhaitera changer la sémantique au niveau du "contenu" du site.
Pour le moment, ceci a été mis en suspend, car cela peut impacter le SEO du site, les internautes ayant plutôt tendance à rechercher des "centres de vaccination" plutôt que des lieux/sites de vaccination :
<img width="1221" alt="centre_de_vaccination__lieu_de_vaccination__site_de_vaccination_-_Découvrir_-_Google Trends" src="https://user-images.githubusercontent.com/603815/114283013-ca296c80-9a47-11eb-9890-bf186ff97216.png">
[source](https://trends.google.fr/trends/explore?date=2020-12-01%202021-04-10&geo=FR&q=centre%20de%20vaccination,lieu%20de%20vaccination,site%20de%20vaccination)

=> je passe le statut de l'issue en suspend

**Comment by nhumblot** [comment]
Les changements sur le contenu qui ont été annulés dans #22 sont disponibles en un seul commit: https://github.com/nhumblot/vitemadose-front/commit/7af94a0f01844f695e3c0672eaff9ec291dc7f73 et pourront être réutilisés si nécessaire.

**Comment by nhumblot** [comment]
À date, le terme *centre de vaccination*, reste hégémonique : https://trends.google.fr/trends/explore?geo=FR&q=centre%20de%20vaccination,lieu%20de%20vaccination,site%20de%20vaccination

Ok pour clôturer ce ticket ? Aucun changement de tendance ne semble se produire au niveau des recherches. Changer les libellés ne semble pas possible sans dégrader notre SEO.

**Comment by fcamblor** [comment]
Yep je suis d'accord
