### ISSUE TITLE
Erreur console avec 97500 - Miquelon-Langlade

### ISSUE THREAD

**Issue by Aymerik** [CovidTrackerFr/vitemadose-front#182]
Lorsque l'on rentre la ville "97500 - Miquelon-Langlade" dans le champ principal, la recherche ne se lance pas, et une erreur console est lancée : 
![image](https://user-images.githubusercontent.com/15689805/117586317-c73d9c80-b117-11eb-860e-9f2478a5d6ec.png)

**Comment by nicolasverlhiac** [comment]
Hello,

Je n'arrive à pas à reproduire ton bug.

<img width="400" alt="Capture d’écran 2021-05-10 à 10 25 40" src="https://user-images.githubusercontent.com/5034521/117629202-364bdd00-b17a-11eb-8118-049384ab7026.png">

@Aymerik, est-ce que tu peux nous en dire un peu plus avec la partie `Network` de la console s'il te plait ?

<img width="1119" alt="Capture d’écran 2021-05-10 à 10 29 48" src="https://user-images.githubusercontent.com/5034521/117629702-ba05c980-b17a-11eb-9020-afcef397af33.png">

**Comment by fcamblor** [comment]
@nicolasverlhiac une fois la commune sélectionnée, c'est là où on a le soucis.

Je pense que ça vient du fait qu'on ait 4 communes qui n'aient ni département ni geolocation dans les metadata d'autocompletes : 
<img width="405" alt="Vite_Ma_Dose___trouvez_un_créneau_de_vaccination_COVID-19" src="https://user-images.githubusercontent.com/603815/117649408-c5172480-b18f-11eb-9d22-fe98eb09f585.png">

Et ce problème vient à priori de l'API geocoding de geoportail qui nous retourne pas ces infos pour ces 4 seules communes de france (j'ai checké sur l'ensemble des communes, seules ces 4 là sont problématiques) : https://geo.api.gouv.fr/communes?codePostal=97500&fields=code,nom,codeDepartement,centre
(alors que [sur 75000 par exemple](https://geo.api.gouv.fr/communes?codePostal=75001&fields=code,nom,codeDepartement,centre) on les a)

Il faudrait peut-être modifier un poil [le tooling de génération des autocomplete](https://github.com/CovidTrackerFr/vitemadose-front/blob/dev/tools/communes-import.js#L115) de communes pour faire en sorte d'enrichir ces 4 communes avec des données "hardcodées" par nos soins ??

**Comment by fcamblor** [comment]
En fait, ce n'est pas un bug, c'est une feature ! :-)

Ces communes ne font par parti d'un département, car il n'existe pas de département 975 / 971 : ce sont des collectivités d'outremer !

Mais du coup, je pense que le soucis est potentiellement un peu plus profond, car on ne dispose du coup pas de fichier JSON de centres pour ces communes :-)

Peut-être faudrait-il suggérer à nos amis du back de rajouter (un jour, quand ils auront du temps :-) ) des scraps sur ces collectivités d'outremer et de nous générer un `om.json` (non, ce n'est pas un JSON pour les Marseillais..)

**Comment by nhumblot** [comment]
FIxed by #218
