### ISSUE TITLE
Autocomplétion du navigateur ( pas du input de vmd!) 

### ISSUE THREAD

**Issue by Olivier4477** [CovidTrackerFr/vitemadose-front#186]
Hello,

J'ai remarqué que mon navigateur se souvient de ma recherche ultérieure sur vmd, donc par exemple il se souvient que j'ai tapé dans le input '57'.

Quand je retourne sur vmd, et que je positionne mon curseur sur la barre de recherche de vmd, j'ai 2 propositions:
La proposition de l'input vmd et la proposition de mon navigateur.
![vmd](https://user-images.githubusercontent.com/68284897/117786672-0d911980-b246-11eb-8d5e-b9ca4028dfc6.JPG)

Donc j'ai les autocomplétion qui se superpose.

Par contre si je clique sur le 57 - Moselle de mon navigateur, le champ vmd va se remplir mais par contre rien ne se charge.
![Screenshot_20210511-104039_Samsung Internet](https://user-images.githubusercontent.com/68284897/117786813-30233280-b246-11eb-96c8-c7c2d7b60329.jpg)

**Comment by bilelz** [comment]
corrigé en prod https://vitemadose.covidtracker.fr/
