### ISSUE TITLE
[SEO]Corrections liens internes vers Vitemadose

### ISSUE THREAD

**Issue by reminesta** [CovidTrackerFr/vitemadose-front#189]
Le lien menu vers Vitemadose n'a pas été mis à jour vers la nouvelle adresse.
<img width="261" alt="2" src="https://user-images.githubusercontent.com/84020427/117817449-e6e3da80-b267-11eb-81aa-e5b90eb29197.PNG">

+ Sur la Homepage dans le listing des outils : 
<img width="282" alt="4" src="https://user-images.githubusercontent.com/84020427/117817666-1abf0000-b268-11eb-972c-557a621cf419.PNG">

=> Remplacer l'URL https://covidtracker.fr/vitemadose/ par https://vitemadose.covidtracker.fr/ sur l'ensemble des liens internes.
Objectif : éviter les redirections internes inutiles + améliorer le référencement de la nouvelle adresse sur Google.

**Comment by Aymerik** [comment]
C'est fait : https://github.com/rozierguillaume/covidtracker-tools/pull/279 :)

**Comment by fcamblor** [comment]
Merci @reminesta je vais fermer l'issue parce que ça n'a pas grand chose avec le front VMD (c'est plus du covidtracker)

@Aymerik je ne vois pas les changements de ta PR mergée sur la prod : c'est parce que ça nécessite une MEP ?

**Comment by Aymerik** [comment]
@fcamblor Il faut que @rozierguillaume ou @nicolinuxfr (ou n'importe qui ayant accès au serveur CT) vide le cache du serveur. Je vais leur demander ! 😉

**Comment by nicolinuxfr** [comment]
Caches WP et CloudFlare vidés.
