### ISSUE TITLE
Retours design 

### ISSUE THREAD

**Issue by adrochet** [CovidTrackerFr/vitemadose-front#19]
- [x] Mettre un placeholder dans l’input des départements « Choisir… » ou « Sélectionner… » 

- [x] Mettre les boutons violets des blocs « VaccinTracker » et « Cartes des centres » à gauche 
- [ ] Utiliser les bonnes tailles et couleurs pour les polices
- [x] Avoir le même height pour les blocs « VaccinTracker » et « Cartes des centres »
- [x] Utiliser la bonne couleur de fond pour les blocs (F6F6F6) 
- [x] Toujours avoir ce résultat même avec une plus grande largeur :
- [x] Mettre l’ancre « En savoir plus » 
- [x] Avoir le même padding sur le côté gauche que haut/bas sur l'input de recherche de département
![image](https://user-images.githubusercontent.com/603815/114300796-3648b680-9ac2-11eb-9e35-5a1d28a99ca7.png)
- [x] Avoir les bons rounded corners un peu partout 
- [x] Augmenter l'espacement entre le séparateur et les liens du coin haut/droit
![image](https://user-images.githubusercontent.com/603815/114300848-609a7400-9ac2-11eb-90c7-aa181de4e9ed.png)

Si il y a besoin d'assets/infos n'hésitez pas :)

**Comment by fcamblor** [comment]
> Mettre les boutons violets des blocs « VaccinTracker » et « Cartes des centres » à gauche

Sur les résolutions mobile, on conserve l'alignement centré, non ?

>  Toujours avoir ce résultat même avec une plus grande largeur :

Il manque une capture je pense :-)

**Comment by fcamblor** [comment]
@alexandreGUY je t'ai assigné sur le RAF, je pense que tu perdras moins de temps que moi sur le sujet :-)

**Comment by adrochet** [comment]
> > Mettre les boutons violets des blocs « VaccinTracker » et « Cartes des centres » à gauche
> 
> Sur les résolutions mobile, on conserve l'alignement centré, non ?
> 
> > Toujours avoir ce résultat même avec une plus grande largeur :
> 
> Il manque une capture je pense :-)

Oui pour le mobile pas de changement. 

Pas besoin de capture apparement car ça a été fait 😄

**Comment by adrochet** [comment]
Petit retour rapide, il faudrait plus d'espace dans le séparateur et les liens

![Capture d’écran 2021-04-11 à 12 12 43](https://user-images.githubusercontent.com/17876938/114300181-44e19e80-9abf-11eb-99b4-95c7584ff4af.png)

Et pour "Avoir le même padding sur le côté gauche que haut/bas" je parle du chevron dans l'input
![Capture d’écran 2021-04-11 à 12 23 07](https://user-images.githubusercontent.com/17876938/114300463-b66e1c80-9ac0-11eb-94f1-d71eb2e3ba77.png)

**Comment by fcamblor** [comment]
Je ferme l'issue car @alexandreGUY en a traité une bonne partie dans la release de ce jour (au pire, s'il reste des remarques, faire des issues spécifiques)
