### ISSUE TITLE
[SEO]Redirection de l'ancienne adresse Vitemadose vers la nouvelle

### ISSUE THREAD

**Issue by reminesta** [CovidTrackerFr/vitemadose-front#190]
L'ancienne adresse https://covidtracker.fr/vitemadose/ redirige vers https://vitemadose.covidtracker.fr/ en redirection 302 (redirection temporaire) au lieu de redirection 301 (redirection définitive).

<img width="347" alt="3" src="https://user-images.githubusercontent.com/84020427/117818137-9caf2900-b268-11eb-9ed3-a965779449d7.PNG">

Il est recommandé en SEO d'utiliser des redirections 301 pour les changements d'adresse, afin que Google mette correctement à jour son index, cf les résultats Google qui remontent toujours l'ancienne URL :

<img width="472" alt="1" src="https://user-images.githubusercontent.com/84020427/117818160-a20c7380-b268-11eb-95c8-2f6592ac14de.PNG">

**Comment by slig36** [comment]
Je propose cette PR pour fix le problème :) https://github.com/CovidTrackerFr/covidtracker-server/pull/6

**Comment by fcamblor** [comment]
Je ferme l'issue car la PR coté server a été mergée merci @slig36 et @reminesta :)
