### ISSUE TITLE
Résultats de Chronodose (très) faux

### ISSUE THREAD

**Issue by darrepac** [CovidTrackerFr/vitemadose-front#191]
Salut

Les résultats de Chronodose, en tout cas en Isère, sont très très faux (donne plein de place de dispo alors que quand on va ensuite sur le lien, il y a 0 places). Peut-être un souci avec Keldoc?

**Comment by Noezor** [comment]
Merci pour ton report, j'ai créé une issue côté back-end :)

https://github.com/CovidTrackerFr/vitemadose/issues/407

**Comment by nhumblot** [comment]
Issue traitée côté back.
