### ISSUE TITLE
Calcul Distances Paris

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose-front#197]
Peu importe l'arrondissement choisi, c'est toujours les mêmes distances aux centres qui sont calculées. J'ai regardé et ça a l'air de coller avec Notre-Dame. Il faudrait mettre 1 centre par arrondissement pour les grandes villes.

**Comment by Noezor** [comment]
De ce que j'ai compris, le calcul de distances se fait [ici](https://github.com/CovidTrackerFr/vitemadose-front/blob/63dfdf3541e1f1b4bd2463c80269f5122bcf0df0/src/views/vmd-rdv.view.ts#L426-L428). 2 Hypothèses : soit `this.communeSelectionnee` porte juste la commune, et pas l'arrondissement. Soit la variable contient bien l’arrondissement, et c'est la résolution de sa location qui se fait mal. 

Si quelqu'un est intéressé

**Comment by bilelz** [comment]
Hello,
Dans cette PR #145 , j'avais identifié que l'identifiant unique d'une commune n'est pas le code mais
`${this.communeSelectionnee.code}-${this.communeSelectionnee.codePostal}`

Ça peut peut-être aider.

**Comment by fcamblor** [comment]
En fait le problème c'est qu'à la base, les geopositions qu'on a récupéré depuis l'API geoportail partagent toutes les mêmes latng (le "code commune" est le même ... il correspond juste à plusieurs "aliases" de code postaux)
<img width="508" alt="Vaccination_COVID-19_à_Paris_75001" src="https://user-images.githubusercontent.com/603815/118277557-337a2080-b4c9-11eb-9319-331a2ece5572.png">

**Comment by fcamblor** [comment]
Du coup soit on override ce comportement (ce serait possible ... on va notamment sûrement commencer à le faire pour les collectivités d'outremer)

**Comment by fcamblor** [comment]
> Du coup soit on override ce comportement (ce serait possible ... on va notamment sûrement commencer à le faire pour les collectivités d'outremer)

Je crois que j'ai pas fini ma phrase :D

Je pense que l'idée c'était de soit overrider manuellement la latng de certains code postaux, soit de laisser tomber :)
