### ISSUE TITLE
Menu déroulants sous Safari pas homogènes au niveau du rendu

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#2]
Cf 
![photo6014918101537240141](https://user-images.githubusercontent.com/603815/114042387-adddd200-9885-11eb-905f-a9f822efd07a.jpg)

**Comment by fcamblor** [comment]
Potentiellement lié à #4

**Comment by nicolinuxfr** [comment]
C'est quoi la différence, à part esthétique ? J'ai le même comportement qu'avec Chrome.

**Comment by alexandreGUY** [comment]
C'est un soucis CSS, Safari ne supporte pas la propriété appearance et bootstrap ne déclare plus les propriétés préfixé.
J'ai fait un fix manuel pour le select, mais ca pourrait mériter un autoprefixer pour s'éviter d'autre problème du genre.
