### ISSUE TITLE
Add PandaLab and MaPharma support (logo etc.)

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose-front#20]

**Comment by fcamblor** [comment]
C'est pas grand chose à faire de mon coté.

Faut-il se synchroniser pour les faire apparaître dans le JSON ? (normalement, s'ils arrivent dans le JSON et que je ne suis pas encore prêt coté front, ce n'est pas grave)

**Comment by Maijin** [comment]
Ils sont ici si besoin - https://github.com/rozierguillaume/covidtracker-tools/pull/251

Sur l'ancien site on pouvait les merge avant d'avoir le JSON de prêt, je ne sais pas si c'est le cas sur la nouvelle version (ce serait pas mal cela dit)

**Comment by fcamblor** [comment]
Normalement c'est le cas (j'affiche juste pas le logo sur la page des résultats, et je ne les mets juste pas dans la liste des plateformes supportées dans la Home)

**Comment by fcamblor** [comment]
fixé, via 9425347
