### ISSUE TITLE
Décompte nombre créneaux et lieux de vaccination différents entre applis et site VMD

### ISSUE THREAD

**Issue by DjMomo** [CovidTrackerFr/vitemadose-front#205]
Bonjour,

Je poste ici un problème qui concernerait plutôt l'affichage au niveau applis, plutôt que le backend (là où j'ai créé l'issue initiale) : https://github.com/CovidTrackerFr/vitemadose/issues/454

**Comment by fcamblor** [comment]
Je pense que c'est lié au fait que la distance utilisée entre applis et site est différente (50km sur les applis, 100km sur le site)

Je close car duplicate de #199 pour moi (quand le site utiliser le fichier firebase, où se trouve cette config, on pourra avoir une gestion homogène des résultats)

**Comment by DjMomo** [comment]
Effectivement, si la limite au niveau des applis est 50kms, les résultats obtenus sont cohérents.
