### ISSUE TITLE
Proposition : créneaux d'ouverture des lieux de vaccination

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#21]
Une proposition de design pour les créneaux d'ouverture
<img width="1358" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114270794-95e58a00-9a0e-11eb-8cb2-5fd2eb8e827d.png">

L'important (pour moi) est d'avoir quelque chose le plus compacte possible (d'où les règles de simplifications sur les jours à créneaux identiques)

Après, il reste à peser le pour et le contre de l'ajout de cette info : utilité vs bruit

**Comment by fcamblor** [comment]
J'ai parké cet improvement sur la branche `creneaux-ouverture-centres`, en attendant qu'on décide de prendre ou d'abandonner :-)

**Comment by nhumblot** [comment]
À clôturer suite au message de @francoisBouchet ? https://github.com/CovidTrackerFr/vitemadose-front/issues/198#issuecomment-846395044

**Comment by nhumblot** [comment]
Clôture du ticket
