### ISSUE TITLE
Ajouter une fonction de réduction de la frustration: Indiquer qu'une dose est déjà prise

### ISSUE THREAD

**Issue by pierri** [CovidTrackerFr/vitemadose-front#221]
En ce moment, pour beaucoup, les chronodoses, c'est pour ceux qui cliquent le plus vite. Et encore, à condition qu'elles ne soient pas uniquement en cache, comme [expliqué](https://twitter.com/GuillaumeRozier/status/1392846470110486529) par GRZ...

Pour **tous les autres** qui arrivent plus tard, au moment de recevoir la notification, c'est :

1. Ouvrir Vitemadose
2. Retrouver le centre de vaccination avec "Chronodoses disponibles" et cliquer sur "Prendre rendez-vous"
3. Sur Doctolib and co., cliquer sur "Prendre rendez-vous en ligne", choisir le motif de consultation par ex. "1re injection vaccin COVID-19" et attendre que la page se charge
4. Constater avec frustration que "aucun rendez-vous n'est disponible pour le moment".

Si on se base sur [des millions de visites pour seulement 1500 doses](https://twitter.com/GuillaumeRozier/status/1392849536624775170), ça fait beaucoup de monde qui se retrouve frustré... Est-ce qu'il serait imaginable de réduire encore plus le nombre d'étapes pour tous ceux-là ?

Une idée serait que les premiers à arriver trop tard puissent indiquer qu'il est déjà *trop tard* pour cette dose. Les suivants verraient dès leur arrivée sur Vitemadose que x personnes ont déjà marqué cette dose comme déjà prise, et éviteraient d'avoir à passer de Vitemadose à Doctolib pour y faire ce constat par eux-mêmes. Et éviteraient de ce fait cette charge aux serveurs de Doctolib... 

Ca permettrait aussi aux premiers qui arrivent trop tard de passer d'une expérience négative (frustration après l'espoir déçu) au sentiment plus positif de pouvoir contribuer à mettre à jour les informations en temps réel pour tous les autres.

**Comment by fcamblor** [comment]
C'est compliqué.

Permettre de flagger des créneaux comme "non présents" nécessiterait : 
- De stocker cette donnée quelque part. N'ayant pas de backend / db, cela ajouterait énormément d'éléments à l'infra existante, en veillant à ce que ces derniers puisse absorber la charge (on parle de millions de visites quotidiennes, ce n'est pas anodin)
- J'ai beaucoup de mal à voir les gens partir de VMD pour aller sur la plateforme de réservation, puis "revenir" sur VMD en mode frustré pour notifier leur frustration

Tout ça dans l'optique où : 
- la frustration pourrait être largement diminuée lorsque le cache doctolib disparaîtra (nous ne sommes pas maîtres de ce point malheureusement...)
- cette fonctionnalité n'aura plus lieu d'être le 15 juin

**Comment by pierri** [comment]
Merci pour la réaction rapide !

Les équipes Doctolib ont-elles déjà communiqué sur un éventuel démantèlement du cache ? 

Et si la vaccination [s'ouvre pour tous le 15 juin](https://twitter.com/lemondefr/status/1388100570863575044), les créneaux mis en ligne ne risquent-il pas également d'être pris d'assaut en provoquant le même type de frustration ?

Je laisse l'équipe en charge de ce repo décider s'il serait judicieux de demander au backend si le stockage du flag "trop tard" y serait envisageable...

**Comment by fcamblor** [comment]
Pour moi c'est trop compliqué.

On mise tout sur l'étalement des créneaux à partir du 31/05 (les gens auront plus de 48h pour faire leur résa ... ce qui devrait fluidifier un peu les choses et diminuer la frustration ... enfin j'espère)

Avec la présentation des créneaux par date proposée dans #233, je pense (j'espère !) qu'on devrait tenir le bon bout pour diminuer la frustration :)

**Comment by fcamblor** [comment]
Je ferme l'issue car je n'ai pas l'impression qu'il y ait énormément de frustrations ces temps-ci :-)

**Comment by pierri** [comment]
👍 

La situation a évolué, et pour la campagne de vaccination actuelle je ne vois plus de nécessité de construire un workaround autour du cache des plateformes de prise de rendez-vous.
