### ISSUE TITLE
Mise-à-jour bandeau

### ISSUE THREAD

**Issue by nhumblot** [CovidTrackerFr/vitemadose-front#222]
Doctolib a diminué son cache à 15 minutes contre 30 minutes. Il faut mettre à jour le message en conséquence.

Source: https://mattermost.covidtracker.fr/covidtracker/pl/dx5idafomfgz9nbaju3cfaka1r
![image](https://user-images.githubusercontent.com/15015617/118702495-49634a80-b815-11eb-9513-440e419762b1.png)

**Comment by fcamblor** [comment]
Avec #207  on uniformiserait le message avec toutes les apps mobile

**Comment by nhumblot** [comment]
Mergée sur `main`.
