### ISSUE TITLE
Filtrer par vaccin

### ISSUE THREAD

**Issue by Rajekevin** [CovidTrackerFr/vitemadose-front#224]
Je me rend compte lorsqu'on fait une recherche, on ne peut pas filtrer par type de vaccin : 
![image](https://user-images.githubusercontent.com/15109096/118813787-c6db9900-b8af-11eb-87fe-d7a1d74c5363.png)

En effet, certains lieux propose seulement de l'AstraZeneca et d'autres plusieurs. 
- Ajouter un filtre par type de vaccin permettra d'exclure certains résultats.

**Comment by Aymerik** [comment]
Hello @Rajekevin

Merci pour la suggestion pertinente. Une issue existe déjà à ce sujet : #147 :-)

Je me permets de fermer celle-ci
Bonne journée
