### ISSUE TITLE
Clikodoc: nouvelle plateforme

### ISSUE THREAD

**Issue by Bouska** [CovidTrackerFr/vitemadose-front#241]
On va implémenter une nouvelle plateforme côté back, il faut donc l'ajouter aux plateformes supportées:

"plateforme": "Clikodoc"

https://www.clikodoc.com/images/home/logo_header_v1.png

**Comment by hmartinez69** [comment]
Je m'en occupe, ce sera ma première issue sur le projet ;)

**Comment by hmartinez69** [comment]
C'est fait de mon côté ;) Le délai moyen de review d'une PR il est de combien de temps ?

**Comment by Luwangel** [comment]
La PR ayant été intégrée à dev, je ferme l'issue. La plateforme Clickodoc fera parti du prochain déploiement.
