### ISSUE TITLE
Bug Geolocalisation arrondissement Paris 

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose-front#245]
Reporté par un utilisateur:

"Que je tape n'importe quel quartier de Paris, il me met toujours le meme au plus proche"

![image](https://user-images.githubusercontent.com/1408600/120229811-3f4a3e80-c24e-11eb-8c20-3a099f65de49.png)
![image](https://user-images.githubusercontent.com/1408600/120229816-41140200-c24e-11eb-9b7e-bd1433460a9f.png)
![image](https://user-images.githubusercontent.com/1408600/120229819-43765c00-c24e-11eb-94ac-367e9eac4ec5.png)

Pas sur si c'est un probleme Front ou Backend (peut etre hybride)

**Comment by fcamblor** [comment]
Je close, duplicate de #197
