### ISSUE TITLE
Breakpoint media sur 1200px qui réduit la plupart des composants

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#26]
@alexandreGUY il existe pas mal d'entrées css avec un `@include media-breakpoint-up(xl)` qui "réduisent" la taille de certains élément dès lors qu'on passe sur une résolution >1200px

Par exemple :
- Le menu de sélection du département
- Le titre h1 de la home
- La taille des cards rdv

Est-ce fait sciemment ?

**Comment by fcamblor** [comment]
Vu avec Alex ce matin :
- Le fait que les largeurs soient réduites est fait sciemment, car sur desktop, les faire prendre toute la largeur n'était pas harmonieux (je confirme)
- Le fait que les tailles de police re-diminuent au-delà de `1400px` est fait par bootstrap. Il faudrait peut-être surcharger ce comportement juste pour la partie recherche en haut.

**Comment by nhumblot** [comment]
À clôturer vu que #49 a été mergée ?
