### ISSUE TITLE
Aucun résultat si accès par url

### ISSUE THREAD

**Issue by grubounet** [CovidTrackerFr/vitemadose-front#276]
Les accès par URL (exemple - https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt75-paris/recherche-dose_rappel) ne renvoient pas de résultats

![image](https://user-images.githubusercontent.com/31167642/147359878-42f7c363-8f2f-4f02-ae6e-c84b492d43a1.png)

**Comment by fcamblor** [comment]
Je précise : le problème ne survient que sur la bookmarkabilité des URLs de recherche par département

Lorsqu'on recherche par code postal on n'a pas le soucis, par exemple : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt33-gironde/commune33550-33140-villenave_d_ornon/recherche-dose_rappel/en-triant-par-distance

**Comment by fcamblor** [comment]
fixed through 0cb604f5
