### ISSUE TITLE
L'application n'est pas fonctionnelle lors d'un accès direct via une URL

### ISSUE THREAD

**Issue by nhumblot** [CovidTrackerFr/vitemadose-front#277]
signalé par @grubounet sur le mattermost

**Étapes pour reproduire**

Accéder à Vite Ma Dose directement via https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt75-paris/recherche-dose_rappel

**Comportement attendu**

Les données sont récupérées et la liste des créneaux disponibles s'affiche pour le département 75 Paris

**Comportement constaté**

Aucun appel n'est effectué pour récupérer les données

**Solution de contournement**

Ctrl + Shift + R pour recharger la page.

**Comment by fcamblor** [comment]
duplicate de #276 ;-)

**Comment by nhumblot** [comment]
Mes excuses, je n'avais pas vu l'issue et voulait la garder pour la traiter. Merci pour le traitement. :)
