### ISSUE TITLE
Réduire la taille des logos

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#30]
Actuellement, on a une empreinte d'environs 200Ko pour les logos

François est en train de nous diminuer ces derniers.

**Comment by fcamblor** [comment]
@francoisbouchet avais-tu pu travailler sur la réduction de la taille des icones (je ne les retrouve pas dans Telegram :( )

=> Si c'est le cas, et pour éviter toute altération par github, il faudrait attacher un zip à cette issue avec ces nouvelles icones :-)

**Comment by francoisBouchet** [comment]
[light assets.zip](https://github.com/CovidTrackerFr/vitemadose-front/files/6308788/light.assets.zip)

bonne mémoire, voici le fichier avec les logos "light" !

**Comment by fcamblor** [comment]
Hello @francoisBouchet,

En regardant la PR #78 fournie par @yannis-mlgrn, je m'aperçois que la taille et surtout la qualité des logo a largement changé, particulièrement sur le logo Maiia.

Avant :
<img width="1315" alt="Vite_Ma_Dose_de_Vaccin___Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/115162497-19a11580-a0a4-11eb-89cf-0446c8ab4414.png">

Après :
<img width="1313" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/115162505-2a518b80-a0a4-11eb-84e9-6312e3ec736f.png">

Je ne suis pas très favorable à intégrer ces logos en l'état, ce n'est pas top pour l'image de ces plateformes

**Comment by francoisBouchet** [comment]
ok... je vais re-regarder ça...

**Comment by francoisBouchet** [comment]
ok vérifié... et retravaillé. 
ci-joint les logos que j'ai alignés dans un html pour vérifier facilement que c'est good. enjoy!

[logos-light-verif.zip](https://github.com/CovidTrackerFr/vitemadose-front/files/6336053/logos-light-verif.zip)

**Comment by yannis-mlgrn** [comment]
hello, je les remplacent par les nouveaux.
bonne soirée !

**Comment by fcamblor** [comment]
@francoisBouchet certains ratio ont changé (cf mon dernier commentaire sur #90 ), c'était fait exprès (pour gagner de l'espace en les retaillant) ou bien ça peut être évité ?

(car changer les ratios signifie qu'il faut qu'on change les css de là où les logos apparaissent pour conserver une proportion homogène entre tous les logos)

**Comment by francoisBouchet** [comment]
je pense que j'avais retaillé les ratios des logos récupérés sur internet car ils ne s'alignaient pas bien entre eux dans mon flex... notamment celui d'Ordoclic qui est placé "très bas" ou Keldoc qui déborde sur avec son picto...

**Comment by francoisBouchet** [comment]
après je suis en train de revoir le layout des cards résultats pour les petites résolutions - je viens de vérifier en prod et c'est pas terrible... - donc je te dirais que ça vaut pas le coup de révisionner le CSS maintenant pour les logos si je te fais tout casser dans quelques heures/demain pour les cards résultats...
