### ISSUE TITLE
Remplacer le copyright du footer

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#31]
Remplacer avec un lien vers le github

**Comment by nhumblot** [comment]
L'objectif de ce ticket est de remplacer "©" par la licence creative common (CC BY-NC-SA 4.0).

"Contributeurs" devient un lien qui pointe vers https://github.com/CovidTrackerFr/vitemadose-front/graphs/contributors

"Vite Ma Dose par CovidTracker" reste du texte sans lien.
