### ISSUE TITLE
Choisir une license

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#32]
Depuis [qu'on link sur le github depuis la home](https://github.com/CovidTrackerFr/vitemadose-front/pull/28/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R82), il serait opportun de définir une license pour le repository

=> MIT, Apache v2 ?

**Comment by nhumblot** [comment]
Corrigé par https://github.com/CovidTrackerFr/vitemadose-front/commit/05f4bee0590aaf6c1ed670b4c30b01a98b1672eb ?

**Comment by fcamblor** [comment]
oui
