### ISSUE TITLE
Nombre d'affichages de centres

### ISSUE THREAD

**Issue by tlevillayer** [CovidTrackerFr/vitemadose-front#37]
Lorsque beaucoup de centres sont répertoriés, ils sont tous affichés sur la meme page.

Pourquoi pas mettre en place un systeme de "pages" avec un nombre de centres affichés maximum à l'écran (10 par ex)

![image](https://user-images.githubusercontent.com/73873761/114304300-b24afa80-9ad2-11eb-83cb-99c1fa42d2b4.png)

**Comment by fcamblor** [comment]
Il faut réfléchir à comment cela va s'articuler avec la double-liste (centres dispos vs centres indispos)

On pagine les 2 listes ?

Ça nécessite un peu de maquetting / intégration également

**Comment by francoisBouchet** [comment]
ok, je vais y réfléchir.  

sur ce template de résultat on a donc à réfléchir à... :
1. on avait amorcé une reflexion sur un paging par timeframe de "7j", est-ce que cela peut être une piste pour ce ticket ? j'ai l'impression que ce ne sera pas suffisant (pour les grandes villes, notamment). 
2.  il y a des filtres par âge / types de vaccin possible... utilisables ? ça arrive à quelle échéance ?
3. aussi, sous-pages "lieux" avec linking interne vers des pages villes ou liées à un code postal unique...

**Comment by fcamblor** [comment]
Avançons petit à petit, tu vois trop loin @francoisBouchet  :-)

Je sais bien que faire un design qui adresse toutes les problématiques est moins coûteux pour toi, mais ça risque de se transformer en une de ces grosses issues énormes à implémenter car elles révolutionnent complètement l'écran.

Je préfèrerais qu'on y aille petit à petit : ici, le sujet est de paginer des résultats.
Comme tu le dis, c'est une problématique qu'on pourra réutiliser plus tard dans tous les cas ... adressons-donc le sujet maintenant (car il pose un problème réel) et on réfléchira aux autres dans un second temps (une autre issue) :)

**Comment by francoisBouchet** [comment]
bin le truc, c'est que je pense que la pagination ne solutionne pas voire complique le fait de trouver un lieu de vaccination proche de chez soi... notamment dans des zones géographiques vastes type Paris IDF, Lyon, Marseille. Créer des écrans intermédiaires, tu perds X% de tes utilisateurs à chaque changement d'écran (et tu en perds moins à les laisser scroller... c'est d'ailleurs une partie du succès de twitter ou facebook --> le rouleau de PQ sans fin... :).

Dans ma carrière d'UX & CRO, j'ai pu drastiquement améliorer les performances des sites en réduisant les écrans (et même de résultats de recherche), plutôt qu'en segmentant sous prétexte de rendre les choses plus digestes.

Donc pour le coup, paginer pour paginer, c'est non pour moi.

**Comment by tlevillayer** [comment]
En fait je pensais pas à rajouter des pages qui changent, mais que tout se fasse dans la meme page, sans redirection, juste du js. C'est possible ?

**Comment by francoisBouchet** [comment]
et rendre les pages plus digestes, c'est plus efficace de le faire par la géographie. une petite ville. aura peu de centres et sa page sera lisible. un arondissement parisien sera également plus "droit au but" que le département parisien.

**Comment by francoisBouchet** [comment]
>  pensais pas à rajouter des pages qui changent, mais que tout se fasse dans la meme page, sans redirection, juste du js. C'est possible ?

j'ai bien compris, mais pour l'utilisateur, l'interaction est la même : un clic. et le coût d'un clic en CRO... $$$
il faut voir une session utilisateur comme un countdown ou une roulette russe avec un nombre limité de clics. plus tu fait cliquer ton user, plus tu as de chances de perdre ton utilisateur. donc à utiliser avec extrême parcimonie.

**Comment by fcamblor** [comment]
@francoisBouchet le truc c'est que nos données sont segmentées par département aujourd'hui

Je te laisse te rapprocher de l'équipe back si tu souhaites militer pour leur faire produire des JSON à un autre niveau géographique, mais je ne vois pas ce point arriver rapidement hônnetement

**Comment by tlevillayer** [comment]
Avant d'etre regrouper par dpt, elles sont aussi stockées de maniere generale : https://raw.githubusercontent.com/CovidTrackerFr/vitemadose/data-auto/data/output/info_centres.json

**Comment by francoisBouchet** [comment]
> 
> 
> Avant d'etre regrouper par dpt, elles sont aussi stockées de maniere generale : https://raw.githubusercontent.com/CovidTrackerFr/vitemadose/data-auto/data/output/info_centres.json

donc si je comprends bien, on a uniquement le code postal dans la string adresse ^^? ou sinon une string ville

**Comment by fcamblor** [comment]
> Avant d'etre regrouper par dpt, elles sont aussi stockées de maniere generale : https://raw.githubusercontent.com/CovidTrackerFr/vitemadose/data-auto/data/output/info_centres.json

Je me vois mal faire télécharger 2Mo à tous les utilisateurs qui font une recherche sur VMD :/

**Comment by tlevillayer** [comment]
> > Avant d'etre regrouper par dpt, elles sont aussi stockées de maniere generale : https://raw.githubusercontent.com/CovidTrackerFr/vitemadose/data-auto/data/output/info_centres.json
> 
> Je me vois mal faire télécharger 2Mo à tous les utilisateurs qui font une recherche sur VMD :/

Pas faux, après est ce que la donnee heures d'ouverture est utilisée ?

**Comment by francoisBouchet** [comment]
non mais on peut faire le "group-by" CP ou ville côté server non ? et venir "hydrater" les pages non ? enfin c'est ce que j'avais cru comprendre par le concept d'hydratation...

**Comment by fcamblor** [comment]
Pour le moment, on n'a aucun serveur

Tout ce qu'on a, c'est des scripts qui viennent préparer la donnée pour qu'elle vienne être consommée ensuite par le front.
(c'est pour ça que j'ai beaucoup de mal quand on parle de recherche pas villes)

**Comment by francoisBouchet** [comment]
on peut clôturer ce ticket.

**Comment by fcamblor** [comment]
Pour info, la pagination permettrait également d'alléger le partie rendering du DOM sur les gros départements (on est actuellement à 62ms de rendering sur le 75 avec 79 centres dispos+indispos, contre 15ms sur un departements avec 0 centres.

=> en gros, 1ms par rdv possible

Bon, je sais pas si on est amenés à arriver au millier de rdv affichés (plus on aura de plateformes, et plus on risque d'avoir des doublons) mais si c'est cas ça peut devenir handicapant.

Clairement, aujourd'hui on est pas sur des nombres qui handicapent la navigation, donc sûrement pas une priorité.

**Comment by nhumblot** [comment]
> on peut clôturer ce ticket.

On peut mettre en place une pagination côté front sinon ? Pas de changement nécessaire côté back, on ne réduit pas la quantité de données récupérée mais ça aura le mérite d'améliorer l'ergonomie ? :thinking: 

Si j'ai bien compris, un trop grand nombre d'éléments entraînait les plantages dans Safari ? Si oui il semble important de passer un peu de temps sur ce sujet.

**Comment by fcamblor** [comment]
Oui, je serais d'avis de faire un infinite scroll à la twitter et afficher par groupe de 20 centres à chaque fois.

Honnêtement ça ne devrait pas être très compliqué à faire.
