### ISSUE TITLE
Changer la branche par défaut de main vers dev

### ISSUE THREAD

**Issue by nhumblot** [CovidTrackerFr/vitemadose-front#40]
Je propose de changer la branche par défaut de `main` à `dev` pour faciliter le processus de développement et de déploiement comme indiqué dans le README :
> dev is the development branch, start any new feature/fix from it.

Cela pourrait faciliter les contributions en ouvrant par défaut les PR sur `dev` et éviterait un besoin de changer la branche de destination comme c'est le cas sur certaines contributions :
* https://github.com/CovidTrackerFr/vitemadose-front/pull/22
* https://github.com/CovidTrackerFr/vitemadose-front/pull/38

**Comment by fcamblor** [comment]
Je suis tout à fait d'accord :)

@rozierguillaume possible de changer cette config ?
Tu devrais pouvoir paramétrer la branche par défaut ici : https://github.com/CovidTrackerFr/vitemadose-front/settings/branches

**Comment by rozierguillaume** [comment]
C’est fait :)

**Comment by nhumblot** [comment]
Super, merci ! :blush:
