### ISSUE TITLE
Scrollbar horizontale sur tel mobile (android)

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#42]
On a une scrollbar horizontale qui est apparue sur tel mobile depuis peu

Il n'est pas impossible que cela soit dû à l'ajout du lien "A propos" dans le header ?

**Comment by fcamblor** [comment]
@alexandreGUY pour info, j'ai toujours la scrollbar (sur mobile en tous cas)

**Comment by nhumblot** [comment]
J'ai commencé à parcourir les anciens commits pour essayer de trouver ce qui a généré le problème.

Commit où je reproduis le bug : 2d1d8624f91e76c0859277794ca39273d81090af
Commit où j'ai un fonctionnement correct : e434c9e7ca38bcc6eb47e3351bbe91b67d1e6425

Je continue demain sur l'identification, ça pourrait nous aider à trouver une solution.

**Comment by nhumblot** [comment]
J'ai menti.

https://github.com/CovidTrackerFr/vitemadose-front/commits/main?before=702006da73832e9c7b83a157045e385f5a35ac9b+245&branch=main

Dernier commit ok : 8283e5ae8ff63ce73851c84f91c8c498ec48caef
Premier commit avec le bug: 17e819bcfd9a0a2737de277562ed4db737bfb3a2

Je regarde demain

**Comment by alexandreGUY** [comment]
C'était les gouttières qui créaient le scrolls, normalement j'avais rajouté le container qui va bien pour l'éviter, mais peut être que j'ai pas appliqué pour qu'il soit aussi sur mobile.

J'arrive pas trop à savoir si c'est moyennement géré par bootstrap cette histoire de gouttière ou si c'est moi qui l'utilise mal.

Je regarde ca entre midi et deux.

**Comment by nhumblot** [comment]
Top, je te laisse faire alors, merci ! :relaxed:

**Comment by alexandreGUY** [comment]
Alors c'était bien encore un soucis de container manquant mais dans le header.

Sur les petits téléphone il y avait aussi un soucis avec le dernier logo des plateformes qui explosait la width.

J'ai fait une PR : https://github.com/CovidTrackerFr/vitemadose-front/pull/113

**Comment by fcamblor** [comment]
J'ai mergé #113 , je ferme :)
