### ISSUE TITLE
Remplacer les icones bootstrap-icons par des icones custom sur fontello

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#43]
Ça permettrait d'améliorer grandement la taille du bundle final (bootstrap-icon représente environ 200Kb...)

[Fontello](https://fontello.com) permet de construire des set de font-icons en allant piocher juste celles dont on a besoin ... et ainsi diminuer drastiquement la taille des assets utilisés

Pour connaître l'ensemble des icones utilisées, il suffit de faire une recherche sur "bi-*" dans les sources

Équivalent des icones utilisées au 11/04/2021 :

Utilisation icone | [Icone bootstrap](https://icons.getbootstrap.com/) | Icone fontello
-------------|---------------|--------------
Location | `geo-alt` | `location` (from: MFG Labs)
Telephone | `telephone-fill` | `phone` (from: elusive)
Type lieu vaccination | `bag-plus-fill` | `commercial-building` (from: Maki)
Arrow up-right pour lien externe | `arrow-up-right` | pas trouvé, mais faisable manuellement
Immeuble, pour stats du nombre de lieux de vaccination avec dispo | `bi-building` | réutiliser `commercial-building` (from: Maki) ?
Check circle pour les stats de proportion de lieux avec dispos | `bi-check-circle` | `ok-circled2` (from: Elusive)
Calendrier avec checkmark OK | `calendar-check-fill` | `calendar-check` (from: font-awesome)
Calendrier avec cross mark | `calendar-x-fill` | `calendar-time` (from: font-awesome)

**Comment by fcamblor** [comment]
Je viens de finir de faire les changements sur la branche `removing-bootstrap-icons`

Différences :
Quoi | Avant | Après
-------|------|--------
Taille du bundle dist (`du -hs`) | 1.4M | 1.1M 💪 
Icone Location | <img width="415" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114322046-73429680-9b1e-11eb-80b9-d0e75724d56d.png"> <img width="88" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114322200-1a273280-9b1f-11eb-9aa6-945fcf7aa8e8.png"> | <img width="379" alt="Image_11_04_2021_23_33_collée" src="https://user-images.githubusercontent.com/603815/114322053-7a69a480-9b1e-11eb-9318-3c41c0d3ebfa.png"> <img width="79" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114467565-67bca180-9bea-11eb-8149-a90d4c7ab6d3.png">
Telephone | <img width="415" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114322046-73429680-9b1e-11eb-80b9-d0e75724d56d.png"> | <img width="363" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114467657-86bb3380-9bea-11eb-9c40-3fd7ea74e548.png">
Type lieu de vaccination | <img width="415" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114322046-73429680-9b1e-11eb-80b9-d0e75724d56d.png"> | <img width="363" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114467723-a18da800-9bea-11eb-9073-84b05abd6399.png">
Arrow up-right lien externe | <img width="134" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114322091-b0a72400-9b1e-11eb-80d4-2eab58095704.png"> <img width="165" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114322102-c0266d00-9b1e-11eb-873c-9978cfed38ba.png"> | <img width="127" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114474718-1d8ded00-9bf7-11eb-817e-533a0863948f.png"> <img width="164" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114474729-27afeb80-9bf7-11eb-9eef-0652466f29e3.png">
Immeuble pour stats du nombre de lieux de vaccination avec dispo | <img width="75" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114322165-f9f77380-9b1e-11eb-94c9-9fcb4bd5d570.png"> | <img width="66" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114467956-00ebb800-9beb-11eb-8fe3-bd5fe825a3c7.png">
Check circle pour les stats de proportion de lieux avec dispos | <img width="94" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114322230-49d63a80-9b1f-11eb-892d-6f8f0c0cd9b4.png"> | <img width="98" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114468015-1c56c300-9beb-11eb-943f-0a4172524490.png">
Calendrier avec checkmark OK | <img width="542" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114322257-696d6300-9b1f-11eb-9a36-3abf32a98613.png"> | <img width="526" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114468073-3690a100-9beb-11eb-9522-e0d2f8502e27.png">
Calendrier avec cross mark | <img width="544" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114322275-86099b00-9b1f-11eb-8711-c7e4a95a33e4.png"> | <img width="553" alt="Le_moteur_de_recherche_d’un_créneau_de_vaccination_contre_la_Covid-19_dans_un_centre_de_vaccination_en_France_" src="https://user-images.githubusercontent.com/603815/114468125-47411700-9beb-11eb-80db-313ae3e19d89.png">


@alexandreGUY  @adrochet @francoisBouchet qu'en pensez-vous ? Il y a des changements qui vous choquent ?

**Comment by francoisBouchet** [comment]
homepage : non, ça ne me choque pas spécialement, même si elles sont moins raffinée (pour celles de la partie statistiques).
page résultat : je garderais les pictos pleins plutôt qu'en path... (il y a déjà bcoup de texte autour, qui sont des "paths" en soi, donc un élément un peu graphique est plus reposant à l'oeil je trouve).

**Comment by fcamblor** [comment]
@francoisBouchet On est d'accords que la colonne de droite c'est le "Après" hein :-D
(ou alors j'ai pas saisi ce que tu entendais par pictos en "paths")

**Comment by francoisBouchet** [comment]
oui, donc pour les deux icônes de la page résultats, conserver les anciennes. 

sinon c'est qu'il y a deux façons de faire de l'illustration vectorielle : dessiner des formes pleines, ou dessiner des tracés.

au moins comme ça on est cohérent sur les deux pages...

**Comment by fcamblor** [comment]
Euh .. désolé, je comprends pas ... qu'entends-tu par forme pleine vs tracé ?

Pour moi un tracé c'est ça :
<img width="74" alt="114322046-73429680-9b1e-11eb-80b9-d0e75724d56d_png__830×354_" src="https://user-images.githubusercontent.com/603815/114323909-b81efb00-9b27-11eb-9a86-7893b3905ba1.png">

Et une forme pleine c'est ça :
<img width="61" alt="114322053-7a69a480-9b1e-11eb-9318-3c41c0d3ebfa_png__758×394_" src="https://user-images.githubusercontent.com/603815/114323927-ca993480-9b27-11eb-813f-ec12db8f4be0.png">

... Et du coup, on avait plutôt des icones en tracés avant, alors qu'après c'est plutôt des formes pleines partout.

**Comment by fcamblor** [comment]
Ah ok je vois peut-être ce qui cloche ... c'est les icones calendar qui sont encore en tracés ?

**Comment by fcamblor** [comment]
(mon soucis, c'est qu'on peut pas dire "on conserve quelques icones comme avant" parce que mon objectif c'est de toutes les enlever pour les remplacer :-) )

Je vais essayer de regarder sur fontello si on a d'autres calendrier un peu plus "pleins" que ceux que j'ai proposé

**Comment by francoisBouchet** [comment]
yep t'as tout bien compris ! 👍

**Comment by francoisBouchet** [comment]
> (mon soucis, c'est qu'on peut pas dire "on conserve quelques icones comme avant" parce que mon objectif c'est de toutes les enlever pour les remplacer :-) )
> 
> Je vais essayer de regarder sur fontello si on a d'autres calendrier un peu plus "pleins" que ceux que j'ai proposé

mais c'est trop lourd d'utiliser un svg séparé ? moi je les affiches comme des images ces deux calendriers...

**Comment by fcamblor** [comment]
Non justement c'est la seule solution qu'on va avoir car je ne trouve pas de font-icon toute prête sur fontello qui arrive à capturer l'intention de nos calendriers (calendrier ok vs calendrier ko)

=> du coup, il faudrait extraire les 2 icones de calendriers parmi la tripotée des icones de bootstrap qui sont dispos là :
[bootstrap-icons.tar.gz](https://github.com/CovidTrackerFr/vitemadose-front/files/6292928/bootstrap-icons.tar.gz)
... pour ensuite se les rajouter dans fontello

**Comment by francoisBouchet** [comment]
j'ai "fontello-ifié" (dans le zip ci-joint), les icônes bootstraps : 

- geo-alt-fill.svg
- telephone-fill.svg
- check-circle-fill.svg
- calendar2-check-fill.svg
- calendar-x-fill.svg

 [fontello-810136ca.zip](https://github.com/CovidTrackerFr/vitemadose-front/files/6296055/fontello-810136ca.zip)


Les svg icônes bootstrap sont aisément récupérables "unitairement" sur https://icons.getbootstrap.com/

**Comment by fcamblor** [comment]
Cool, en effet je n'avais pas fait gaffe qu'on pouvait récupérer facilement les SVG sur le site de bootstrap, ça simplifie :)

Du coup :
- J'ai gardé l' `arrow-up-right` de bootstrap
- Comme demandé, j'ai remplacé les icones en fil de fer par des icones pleines (de bootstrap)

Ce qui donne :
Utilisation icone | Icône avant | Icône après
-------------|---------------|--------------
Location | `geo-alt-fill` (bootstrap) | `geo-alt-fill` (bootstrap)
Telephone | `telephone-fill` (bootstrap) | `telephone-fill` (bootstrap)
Type lieu vaccination | `bag-plus-fill` (bootstrap) | `commercial-building` (from: Maki)
Arrow up-right pour lien externe | `arrow-up-right` (bootstrap) | `arrow-up-right` (provided by ~bootstrap~ Adrien)
Immeuble, pour stats du nombre de lieux de vaccination avec dispo | `bi-building` (bootstrap) | `commercial-building` (from: Maki)
Check circle pour les stats de proportion de lieux avec dispos | `bi-check-circle` (bootstrap) | `bi-check-circle` (bootstrap)
Calendrier avec checkmark OK | `calendar-check-fill` (bootstrap) | `calendar-check-fill` (bootstrap)
Calendrier avec cross mark | `calendar-x-fill` (bootstrap) | `calendar-x-fill` (bootstrap)


J'ai mis à jour [mon commentaire initial comparant avant/après](https://github.com/CovidTrackerFr/vitemadose-front/issues/43#issuecomment-817377861)

@francoisBouchet tu valides ? :)

**Comment by francoisBouchet** [comment]
on valide... j'aime pas la flèche bootstrap (upright) et préfère celle d'Adrien (je crois que je te l'avais fourni en fontello. mais si tu ne l'as pas sous la main. passe en prod !

**Comment by fcamblor** [comment]
Ah j'avais pensé que ça avait été l'inverse en fait (je pensais que celle qu'on avait était celle d'Adrien, et que celle que tu m'avais filé un copycat :-) )

Je l'intègre
