### ISSUE TITLE
insertion de tags Google Analytics / Google Tag Manager

### ISSUE THREAD

**Issue by francoisBouchet** [CovidTrackerFr/vitemadose-front#48]
# TAG à placer dans le head de chaque page

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KWWTRTX');</script>

# TAG à placer juste après le body tag

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KWWTRTX"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by francoisBouchet** [comment]
méchant Google ! vilain ! (NB: on cherche surtout à savoir combien de visites récupère VMD, combien de clics on génère en direction des plateformes de santé... sans effectuer un tracking complet de la conversion sur ces dernières... sans liaison non plus avec des systèmes publicitaires).

**Comment by francoisBouchet** [comment]
ai trouvé des instructions pour "anonymiser" cette collecte de données via GA. lien : https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization

**Comment by fcamblor** [comment]
Vu sur Telegram : on va rajouter une mention dans la section `A Propos` au sujet des données qu'on capture, juste avant le paragraphe "Vite Ma Dose n'est pas un outil officiel [...]" :
```
Mesure d'audience : afin de vérifier le bon fonctionnement de notre site internet, nous effectuons
<strong>une mesure anonymisée</strong> de l'utilisation du site. A l'exception de ces données de navigation, nous ne partageons
aucune donnée collectée avec d'autres entreprises. Vite Ma Dose ne collecte aucune données personnelles.
```
