### ISSUE TITLE
Les cards de réservation ne sont pas focusables

### ISSUE THREAD

**Issue by arnaudforaison** [CovidTrackerFr/vitemadose-front#56]
# Actuellement
Lorsque j'appuie sur tab après avoir fait la recherche le focus est mis sur la liste déroulante, si je ré-appuie sur tab s'arrive en bas de page sur le bouton du 1er centre sans créneaux de vaccination

# Suggestion
Après la recherche avoir le focus directement sur le 1er rdv disponible et si je continues à appuyer sur tab alors je descends dans la liste des rdv.
Voir si je passe avant par la nouvelle fonctionnalité " de distance"

**Comment by fcamblor** [comment]
La pr #53 traite de cette issue

**Comment by fcamblor** [comment]
PR #111 traitant de cette issue (la #53 a été fermée hier)

**Comment by fcamblor** [comment]
Je ferme l'issue car #111 a été mergée :-)
Preview visible ici : https://dev.vitemado.se/dev/
