### ISSUE TITLE
Rendre cliquable l'adresse

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#58]
Avec un `geo:latng`

Attention : ça ne fonctionne visiblement pas sous Safari, cf https://github.com/CovidTrackerFr/vitemadose-front/pull/47

**Comment by fcamblor** [comment]
ping @nhumblot

**Comment by nhumblot** [comment]
Les échanges dans la PR évoquent l'utilisation ou la création d'un polyfill pour gérer les navigateurs qui ne gèrent pas les urls `geo:`, entre autre Safari.

>On pourrait essayer d'améliorer rendAddress() en devinant un support ou non des urls geo: via un polyfill pour conserver la fonctionnalité pour les systèmes qui le supportent et faire une redirection GMaps (ou open street map ? ou autres ?) pour ceux qui ne le font pas ?
>
>Exemple: https://github.com/prowestgis/dojo-geo-uri-polyfill
>
>J'ai recherché très rapidement, il faudrait déjà voir si un tel polyfill "à jour" existe et si la licence permet sa récupération. Sinon il faudrait en faire un nous-même.

Le polyfill indiqué ne convient pas car nécessite l'utilisation de dojo qui est très volumineux.

Il faudrait néanmoins tester son fonctionnement pour valider la faisabilité et envisager d'implémenter un polyfill avec une fonctionnalité équivalente. Je n'ai pas été en mesure de trouver un autre polyfill.

Un revert de ce [commit](https://github.com/CovidTrackerFr/vitemadose-front/commit/2f3797ff61452b7f17b4d4914626a744b741ded4) sur le code actuel est une base de départ pour intégrer le polyfill.

**Comment by bilelz** [comment]
Hello, une alternative à `geo:latng` serait de faire pointer le lien vers la map d'Apple
[http://maps.apple.com/?address=163 Boulevard du Mercantour, 06200 Nice&ll=43.6789432,7.2000901
](http://maps.apple.com/?address=163%20Boulevard%20du%20Mercantour,%2006200%20Nice&ll=43.6789432,7.2000901
)
- sur les devices Apple : ça ouvre Plans
- le reste du monde : ça redirige vers Google maps

https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html

**Comment by francoisBouchet** [comment]
hello, j'apporte mon point de vue "rabat-joie" d'UX et CRO mais perso je ne rendrais pas l'adresse cliquable.

- on a déjà un indicateur de distance. même si on ne connait pas l'adresse exacte on sait tout de même si ça vaut le coup ou pas.
- la fonction première de cette card est de propulser l'utilisateur sur les plateformes de santé... multiplier les clics "autres" c'est multiplier les chances de faillir à cette mission. c'est multiplier les chances de perdre l'utilisateur sur un site tiers (Google ou Apple dans le cas présent), alors que notre mission était de l'envoyer chez Docto, Keldoc ou autre où toutes ces infos sont visibles.

**Comment by bilelz** [comment]
> hello, j'apporte mon point de vue "rabat-joie" d'UX et CRO mais perso je ne rendrais pas l'adresse cliquable.
> [...]

OK
Une solution simple pour permettre à l'utilisateur de sélectionner l'adresse et faire lui-même la recherche dans google maps (ou autre) : 
- désactiver le click sur toute la carte qui empêche la sélection de texte


![image](https://user-images.githubusercontent.com/1426314/118464232-e97b7f80-b700-11eb-8079-b1d1d329d7fe.png)

Je ferai une PR pour voir ce que ça donne. (surtout que j'aime bien faire des click droit sur une adresse)

**Comment by nhumblot** [comment]
Corrigé par #195
