### ISSUE TITLE
SEO - besoin de balises title personnalisées par "pages"

### ISSUE THREAD

**Issue by francoisBouchet** [CovidTrackerFr/vitemadose-front#61]
**Balise TITLE homepage :**  
Vite Ma Dose : trouvez un créneau de vaccination COVID-19

**Balise TITLE page département**
pattern : "Vaccination COVID-19 en [NOM-DPT] [DPT-ID]"
Vaccination COVID-19 en Alpes de Hautes Provence 04

**Comment by fcamblor** [comment]
@francoisBouchet  Tu parles des `<h1>` ou du `<meta title>` (ou les deux) ? :-)

**Comment by francoisBouchet** [comment]
<title> ... </title>

**Comment by fcamblor** [comment]
Indication d'implémentation pour qui voudrait tacler cette issue : ça devrait s'implémenter assez facilement dans le `Router.ts` :
- Définir pour chaque route un `title`
- Lors de la navigation sur une route, aller modifier le `<title>` de la page via un coup de JS

**Comment by fcamblor** [comment]
@francoisBouchet on a fixé le `<title>`

Par contre je me demandais... ne devrait-on pas aligner le `<meta title>` (et potentiellement le `<h1>`) à chaque fois qu'on navigue ?

**Comment by francoisBouchet** [comment]
c'est clairement pas une "best-practice" (old hack que Google détecte facilement, sans forcément).

> Certains outils SEO envoient une alerte lorsque title et H1 sont identiques (ScreamingFrog, SEMrush…). Pourtant, aucune étude ne permet d’affirmer que c’est une erreur.
>99% des E-commerces dans le monde possèdent le même title et le même H1… sans être pénalisés.

source: https://internetbusiness.fr/balise-titre-h1-identiques/

sinon on peut "centraliser" les meta (titles et autres) dans un fichier à part et l'injecter dans chaque page pour t'en simplifier la gestion ? mais ça va demander un peu de dév pour un impact qui me paraît négligeable.

des balises titles dédiées et plus courtes - 60 caractères espace compris max - ce sera aussi bcoup plus pratique dans notre Analytics où chaque page remonte avec un titre hyper-long (et le même).. et nous oblige à switcher de view pour repasser en url-paths...

**Comment by fcamblor** [comment]
> sinon on peut "centraliser" les meta (titles et autres) dans un fichier à part et l'injecter dans chaque page pour t'en simplifier la gestion ? mais ça va demander un peu de dév pour un impact qui me paraît négligeable.

C'est franchement rien à faire, on a déjà fait en sorte de mettre un `<title>` pour chaque page ... doublonner pour le `meta title` ne serait vraiment pas compliqué/chronophage à faire.

La principale question est de savoir si on veut y aller ou pas : tu me dis :)
