### ISSUE TITLE
Remplacer l'icone commercial-building de Maki par la building de font-awesome

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#63]
Le site Maki est pas top pour récupérer un SVG unique d'une icone (pouvoir récupérer facilement une icone peut être  utile pour plein de bonnes raisons, comme par exemple pouvoir partager avec l'équipe mobile ces icones...)

=> J'aimerais intégrer celle-ci à la place (disponible de base dans fontello) : https://fontawesome.com/icons/building?style=solid

**Comment by PACMAN49** [comment]
bonjour j ai préparé une correction mais je ne peux pas pousser ma brancher pour créer le PR. Pouvez me donner les droits en push ?

**Comment by Benvii** [comment]
Bonjour @PACMAN49 j'ai l'impression que tu n'as pas fork ce dépôt, pour contribuer il faut travailler sur ton fork puis envoyer un PR depuis le dépôt de ton fork vers le dépôt (base).

N'hésites pas à regarder ce tuto :  https://github.com/firstcontributions/first-contributions

**Comment by yannis-mlgrn** [comment]
hello, j'ai vu qu'il avait close sa PR. Les changements son toujours à faire ?

**Comment by Benvii** [comment]
L'icon commercial-building Maki est toujours présent : 
*  [src/components/vmd-appointment-card.component.ts#L191](https://github.com/CovidTrackerFr/vitemadose-front/blob/dev/src/components/vmd-appointment-card.component.ts#L191)
* [src/views/vmd-home.view.ts#L135](https://github.com/CovidTrackerFr/vitemadose-front/blob/dev/src/views/vmd-home.view.ts#L135)

Tu prends cette issue @yannis-mlgrn  ?

Le code de @PACMAN49 n'a jamais été mergé car il incluait des diff de linter qui n'avaient pas de lien avec l'issue.

**Comment by yannis-mlgrn** [comment]
oui, je pense que je vais partir dessus

**Comment by hmartinez69** [comment]
Ducoup cette issue est traitée ou pas ?

**Comment by nhumblot** [comment]
Il y a déjà la PR #235 qui a l'air bien. Je ne pense pas que ce soit nécessaire d'en ouvrir une autre. :slightly_smiling_face:
