### ISSUE TITLE
Créer une page dédiée aux Crédits, pour remercier tous les contributeurs

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#64]
Crédits à ne pas oublier :
- Design d'@adrochet
- Liste exhaustive des contributeurs au code récupérable par API Github ???
- SEO par @francoisbouchet
- Liste exhaustive des contributeurs aux issues récupérable par API Github ???

**Comment by francoisBouchet** [comment]
je prépare un petit truc fun... ;)

**Comment by nathanfallet** [comment]
Peut être diviser la liste par morceau, par exemple pour la partie fetch via GitHub par repo (back/front/ios/android)

Linked with https://github.com/CovidTrackerFr/vitemadose/issues/228
