### ISSUE TITLE
Proposition de modifier le "sélectionner" dans le champ de sélection du département

### ISSUE THREAD

**Issue by lc-dx** [CovidTrackerFr/vitemadose-front#67]
![Capture d’écran 2021-04-13 à 19 27 13](https://user-images.githubusercontent.com/82411720/114595063-41504200-9c8e-11eb-8092-8858016b07c7.png)

Etant donné que la phrase d'accroche est **votre vacc[...]**, je propose deux pistes :

1. écrire "sélectionnez" en lieu et place de "sélectionner..."
2. supprimer "Mon département :" et remplacer par "Sélectionner votre département" dans le champ (je ne sais plus comment ça s'appelle)

**Comment by fcamblor** [comment]
@francoisbouchet @adrochet un avis ? :)

**Comment by francoisBouchet** [comment]
1. oui, c'est une best-practice... même si je l'ai toujours trouvée assez "impérative" :)

2. plusieurs solutions... avec différents avantages et inconvénients.

En règle générale, on préfère garder un label associé à un champ de formulaire pour des raisons d'accessibilité. (encore faut-il que l'on soit dans un véritable form avec un submit... mais j'ai l'impression qu'on est dans un div avec un comportement javascript associé) 

**Afficher le label dans l'input**
Visuellement, on peut bidouiller la CSS pour fusionner et donner l'impression que le label s'affiche à l'intérieur l'input. (mais bon, vu qu'on l'affiche en petit, si tu as des problèmes de vue... tu as créé un nouveau problème^^). c'est ce qu'a fait Airbnb (mais je trouve ça moins pratique / tout rikiki VS ce qu'ils avaient avant).
![Screenshot 2021-04-14 at 09-14-45 Vacation Rentals, Homes, Experiences Places - Airbnb](https://user-images.githubusercontent.com/36815410/114669566-536bc800-9d02-11eb-920b-a919d3ba63f9.png)

J'ai l'impression que SNCF/OUI a choisi une autre voie, avec encore plus de JS, mais intéressante : 
on a l'impression de voir un placeholder dans l'input. mais quand on clique, il se déplace au-dessus du champ : c'était le label ! on reste assez respectueux de l'accessibilité et de la lisibilité.

default: 
![Screenshot 2021-04-14 at 09-21-27 OUI 01](https://user-images.githubusercontent.com/36815410/114670218-0f2cf780-9d03-11eb-9d6e-d4830c977f99.png)
active: 
![Screenshot 2021-04-14 at 09-21-27 OUI 02](https://user-images.githubusercontent.com/36815410/114670279-1e13aa00-9d03-11eb-8878-e5754bd266f1.png)

--> à voir si vous arriver à reproduire cela ou à emprunter leur bout de code sur cet élément. en tout cas c'est mon implémentation préférée des deux mastodontes du tourisme en ligne :)

**Comment by francoisBouchet** [comment]
quelques tutos trouvés sur les zinternets : 

label inside input : 
https://codepen.io/jdax/pen/mEBJNa

tutoriel assez exhaustif (vers le milieu de page il y a le comportement sncf)
https://itnext.io/how-to-build-a-floating-label-input-field-f9b21669fe2f

NB: tous les exemples trouvés sont sur des input text... et pas sur un select... mais la semaine dernière quand j'intégrais l'index de VMD, j'utilisais une technique similaire pour personnaliser l'affichage des arrows du select. donc ça devrait le faire...

**Comment by lc-dx** [comment]
Content que mon idée crée des émules. En effet je suis d'accord il ne faut pas perdre de vue l'accessibilité à l'outil qui doit rester au cœur de la réflexion. 
La proposition de solution type Sncf semble pas mal à voir comment elle peut évoluer si on ouvre à la sélection par ville qui si je ne me trompe pas est dans les tuyaux.

**Comment by fcamblor** [comment]
Alors pour moi il y a 2 sujets (j'aimerais éviter de mélanger les issues) : 
- 1 sujet sur la sémantique ("Sélectionnez", "Sélectionner" etc..)
- 1 sujet sur l'ergonomie sur les inputs de formulaire (et oui @francoisBouchet, je préfère aussi la solution SNCF, mais attention car le public cible étant potentiellement agé, on a toujours fait en sorte de mettre de "grosses" polices, à minima aux moments où on demande une information à l'utilisateur

Le truc, c'est que les 2 sujets ne demandent pas du tout la même énergie pour être taclés, d'où ma proposition de splitter dans une issue à part ta proposition ergo François (possible que l'un de vous s'en occupe ?)

Sur l'issue courante, concentrons-nous sur la sémantique si ça vous va bien
Et je comprends de la réponse de François que c'est un Go pour passer à l'impératif dans le libellé.
@lc-dx tu te charges de faire une petite Pull Request ? Ce serait un bon exercice pour un premier début ;-)

**Comment by lc-dx** [comment]
Ok c'est noté je regarde ça ce soir après le taf pour la modification à l'impératif. 
En effet ça va être un bon entraînement 😃 !

**Comment by fcamblor** [comment]
Fixé, via #76
