### ISSUE TITLE
Permettre de sélectionner une commune en guise d'alternative à la géo-localisation

### ISSUE THREAD

**Issue by nhumblot** [CovidTrackerFr/vitemadose-front#68]
Certains utilisateurs peuvent ne pas vouloir utiliser la localisation
D'autres voudraient pouvoir regarder les centres à proximité d'une commune pour effectuer une simulation pour un proche

Demande originale : https://twitter.com/Chapy92/status/1382023064406290432?s=20

**Comment by fcamblor** [comment]
L'idée de @Floby (que je partage car triviale à implémenter) :
- Faire en sorte de générer 1 fichier JSON pour chacun des code postaux de France. Chaque fichier contiendrait :
  - Le ou les noms correspondant aux communes correspondant à ce code postal
  - Une latng correspondant au Barycentre du Polygone issue de la/des communes 
  - Le code département de la commune (notamment utile pour la Corse où ça peut être difficilement déterminé en l'extrayant du code postal)
- Ces fichiers seraient pré-calculés une fois pour toutes, à partir d'outillage permettant d'automatiser leur création, et se basant sur des contenus opendata de la liste des communes et des polygones définissant chaque communes
  ⬆️ _Pointeurs opendata à trouver.._
- Je ne sais pas trop où on pourrait stocker ces fichiers (peut-être les faire fournir par le back)
- Coté UI, on demanderait à l'utilisateur de saisir le CP et on requêterait le fichier json correspondant
  - Si non trouvé : affichage d'un message d'erreur comme quoi le code postal semble invalide
  - Si trouvé, affichage du nom des communes, et navigation vers la page de résultats pour le département de la commune
  - Pré-sélection du tri par distance par défaut, en considérant que la position de l'utilisateur est celle du barycentre du CP

**Comment by fcamblor** [comment]
PR #82 traitant de ce sujet
