### ISSUE TITLE
Retirer le critère d'age dans l'url de la page de résultats

### ISSUE THREAD

**Issue by nhumblot** [CovidTrackerFr/vitemadose-front#69]
Exemple d'url actuelle : `https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt05-hautes-alpes/age-plus75ans/`

Il faut utiliser plutôt utiliser `https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt05-hautes-alpes`.

`age-plus75ans/` prête à confusion et certains utilisateurs ont pensé qu'ils n'étaient pas éligibles.

On supportera les deux urls le temps du déploiement. Une fois le déploiement effectué, il faut mettre en place une redirection 301 de l'ancienne url vers la nouvelle pour éviter une duplication de service du contenu qui pourrait dégrader le référencement.

**Comment by fcamblor** [comment]
OK avec la PR

Avant que je ne la merge, pourrais-tu créer une issue (voire même, idéalement une PR ???) sur https://github.com/CovidTrackerFr/covidtracker-server pour faire en sorte de proposer la redirection ?

L'idée serait d'attendre que le fix soit validé (sans être déployé) pour qu'on merge la PR courante
=> comme ça on pourra s'aligner rapidement lors de la MEP de cette PR

**Comment by nhumblot** [comment]
- Création de https://github.com/CovidTrackerFr/covidtracker-server/pull/4 pour changement de configuration sur l'environnement de développement
- Création de https://github.com/CovidTrackerFr/covidtracker-server/pull/3/ pour changement de configuration sur l'environnement de production

**Comment by nhumblot** [comment]
Proposition de déploiement de la feature:

1. Déployer #70 sur l'environnement de dev
2. Valider le changement
3. Reporter #70 sur toutes branches déployées sur dev
4. Déployer https://github.com/CovidTrackerFr/covidtracker-server/pull/4 pour tester sur dev et valider la redirection
5. Déployer #70 en prod
6. Déployer https://github.com/CovidTrackerFr/covidtracker-server/pull/3 pour apport la redirection en prod

**Comment by fcamblor** [comment]
@nhumblot la suppression des tranches d'age est dispo sur https://dev.vitemado.se/simplified-search-by-commune/

Pourras-tu checker le point 4/ et voir pour faire le point 5/ si OK ?

**Comment by nhumblot** [comment]
Une recherche sur https://dev.vitemado.se/simplified-search-by-commune/centres-vaccination-covid-dpt05-hautes-alpes/age-plus75ans/ affiche une page blanche `Not found`. C'est ko pour moi, le routeur front ne gère plus l'ancienne url et on en a besoin pour faire le changement en douceur le temps de déployer la règle côté serveur http.

Ou alors on ne tient pas compte de ce cas ? Mais on va perdre tous les utilisateurs qui ont bookmarké et copié le lien.

**Comment by fcamblor** [comment]
On est bons sur https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt05-hautes-alpes/age-plus75ans/ ;-)

(en fait, le problème c'est que le serveur de dev ne fait pas un forward sur index.html ... tu peux refresh aucune des pages en fait)
