### ISSUE TITLE
S'occuper du SEO

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#7]
Je quote @rozierguillaume :

> Pour l’intégration du front, niveau SEO il faudrait :
> 
> Mettre en haut du site un \<title\>, une meta-description, ainsi qu’un \<H1\> 
> 
> Puis en bas de la page il faudrait faire quelques paragraphes avec des titres \<h2\> et des paragraphes \<p\>

**Comment by alexandreGUY** [comment]
@fcamblor Le title est présent, le h1 c'est OK, les h2 et les p également.

Manque juste la description en vrai.

**Comment by fcamblor** [comment]
- [x] Yep, mais comme évoqué [ici](https://github.com/WICG/webcomponents/issues/500), le fait que cela soit dans le shadow root n'est à mon avis pas une bonne chose, il faudrait rendre les partie statiques "communes" disponibles sous forme d'un `<slot>` dans le `index.html` (en croisant les doigts pour que les robots sachent aller regarder dans cette balise slot)

- [ ] Autre document important à prendre en considération (il y a plein plein de petites sous-tâches à faire là-dedans) : https://docs.google.com/document/d/1UmFsXcC5SVeRJYsIoUz4me7bc9aYTi-FyQQzKlLk5sc/edit#heading=h.moh23uhqxt0t

**Comment by fcamblor** [comment]
Je ferme l'issue, car je pense qu'@Aymerik  en avait fait une bonne grosse partie :-)
(s'il en manque, créer des issues spécifiques)
