### ISSUE TITLE
Centre indisponibles : rajouter numéro de tel + implémenter un tri

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#73]
Le numéro de téléphone est une information qui semble être utile sur les centres indisponibles, il serait intéressant de les afficher.

D'autre part, après discussions avec Maijin du back, il apparaît que certaines plateformes (Doctolib à minima) considèrent le téléphone comme le seul **MOYEN** de prise de rendez-vous sur certains centres :
![image](https://user-images.githubusercontent.com/603815/114636444-572e2900-9cc7-11eb-9e91-d51441d04145.png)
_ce message n'apparaissant pas par manque de créneaux de réservation sur le centre, mais bel et bien parce que c'est le **MOYEN** de prise de rdv pour le centre_

Il semble que le back puisse être en mesure de pouvoir détecter ces cas de figure.
Si c'est bien le cas : il faudrait s'interroger sur la possibilité d'afficher différemment le bloc centre indisponible.
Par exemple **en considérant que l'url du centre devrait être ignorée** (_cette règle pourrait être implémentée coté back_) et **en affichant un bloc suggérant d'appeler le centre au numéro de ce dernier**, en lieu et place du bouton permettant de naviguer sur la page du centre sur la plateforme (et qui n'afficherait rien de plus qu'un message préconisant d'appeler le numéro)
=> On éviterait ainsi un clic inutile pour l'utilisateur, tout en allégeant un affichage de page sans grosse plu-value coté plateforme.

En tout état de cause, il faudrait changer le tri des centres indisponibles pour trier dans l'ordre suivant :
- Les centres indispos disposant d'un lien
- Les centres indispos sans lien mais avec un numéro de téléphone (en affichant peut-être en premier les centres où la prise de rdv par tel est le MOYEN de prise de rendez-vous principal, cf cas évoqué précédemment)
- Les centres indispos sans lien ni numéro de téléphone

**Comment by Maijin** [comment]
Pour les numeros de telephone il y a aussi ces deux issues pour info:

https://github.com/CovidTrackerFr/vitemadose/issues/197
https://github.com/CovidTrackerFr/vitemadose/issues/180

**Comment by aureliancnx** [comment]
Pour le back :

J'ai ajouté la clé appointment_by_phone_only dans chaque centre. `True` si le centre n'accepte que des rendez-vous par téléphone, `False` pour l'inverse.

Evidemment, chaque centre ne proposant que des rendez-vous par téléphone sont dans la liste `centres_indisponibles` des JSON des départements.

C'est fait pour Doctolib & Ordoclic. L'implémentation avec le reste devrait être facile.

-- 

Si vous avez l'envie de faire un affichage spécial pour ces centres, vous pouvez, maintenant.

**Comment by Maijin** [comment]
Perso je verrai bien un truc du style:

Dans cet ordre:
-> Centre avec rendez-vous en ligne dispo - bouton cliquez ici pour resa
-> Centre avec rendez-vous par telephone - bouton cliquez ici pour telephoner
-> Centre avec rendez-vous "inconnu"
-> Centre qui ont eu des rendez-vous mais actuellement sans doses - pas de bouton et grisé

**Comment by aureliancnx** [comment]
> Perso je verrai bien un truc du style:
> 
> Dans cet ordre:
> -> Centre avec rendez-vous en ligne dispo - bouton cliquez ici pour resa
> -> Centre avec rendez-vous par telephone - bouton cliquez ici pour telephoner
> -> Centre avec rendez-vous "inconnu"
> -> Centre qui ont eu des rendez-vous mais actuellement sans doses - pas de bouton et grisé

J'ai pas trop d'avis sur l'idée de séparer les centres avec des RDV inconnus et ceux qui en ont eu & qui n'en n'ont actuellement plus de dispo, je laisse les experts de l'UX juger.

Sinon, pour l'idée de séparer les RDV en ligne dispo & les RDV par téléphone, je trouve ça une bonne idée. Afficher le numéro de téléphone directement et le rendre cliquable (et peut être différencier un peu le bouton avec pour téléphoner / prendre rendez-vous en ligne, pour que ce soit visible instantanément pour l'utilisateur ?)

Pour les personnes qui argumenteraient sur cette feature en disant que les centres qui ne proposent pas de rendez-vous en ligne vont être submergés d'appels même s'il n'y a aucune dispo... c'est un peu de la faute du centre qui n'autorise pas la prise de rendez-vous en ligne & donc sollicite inutilement des centres. Ceci dit, les centres ont parfois des listes d'attente quand ils n'ont pas de doses et qu'ils sont sollicités, il vaut mieux plus de demande que d'offre que l'inverse..

**Comment by fcamblor** [comment]
> J'ai ajouté la clé appointment_by_phone_only dans chaque centre. True si le centre n'accepte que des rendez-vous par téléphone, False pour l'inverse.

~@aureliancnx je ne trouve pas ce nouveau champ en prod, le changement a été promu jusqu'à votre prod ?~

EDIT: J'ai rien dit... je checkais github et non gitlab :-)

**Comment by fcamblor** [comment]
Quelques questions :
- Je vois que pour le moment, ce champ n'est présent que sur des centre indispos ET avec 0 `appointment_count` => ne pourrait-on pas avoir, par la suite, des centres avec des doses (donc dans `centres_disponibles`) et avec résa tel uniquement (`url` vide) ?
- Je vois que pour le moment, l' `url` est systématiquement définie ... êtes-vous d'accords pour dire qu'on pourrait avoir un jour des centres sans `url` définie ?

**Comment by Maijin** [comment]
1. Je vois que pour le moment, ce champ n'est présent que sur des centre indispos ET avec 0 appointment_count => ne pourrait-on pas avoir, par la suite, des centres avec des doses (donc dans centres_disponibles) et avec résa tel uniquement (url vide) ?

-> Cela voudrait dire que les centres soient en mesure d'afficher le nombre de dose disponible sans ouvrir la prise de rendez-vous en ligne. En theorie, j'imagine que cela serait possible dans un future ou c'est affiché sans prise de rendez-vous en "pour info". Mais le cas ne s'est jamais présenté pour aucune des plateformes disponibles.

2. Je vois que pour le moment, l'URL est systématiquement définie ... êtes-vous d'accords pour dire qu'on pourrait avoir un jour des centres sans url définie ? 

-> On recupere l'information "appointment_by_phone_only" via l'URL. En theorie donc, on ne devrait donc jamais avoir de centre sans URL. Cela-dit, il est possible qu'un jour, un centre qui n'utilise pas de plateforme, nous approche manuellement ou via datagouv sans URL associé a une plateforme.

**Comment by aureliancnx** [comment]
1. Non c’est impossible. Le nombre de "doses" est récupéré par rapport au nombre de créneaux disponibles à la réservation en ligne

**Comment by fcamblor** [comment]
OK merci de vos retours 👍

**Comment by fcamblor** [comment]
La vision que j'avais partagé mardi sur le channel Design serait de "rassembler" les actuelles deux listes pour ne plus en avoir qu'une seule triée de la manière suivante :
- Tous les centres où **"on peut réserver en ligne"** => clair + bouton violet envoyant vers la plateforme
- Tous les centres où **"il faut appeler pour réserver"** => clair + bouton d'une autre couleur avec le numéro de tel dedans (et un lien en tel: )
- Tous les centres où **"d'hab, on peut réserver, mais actuellement il y a 0 doses"** => clair + bouton violet (ou de l'autre couleur si tel uniquement) "grisé" (=plus clair, non cliquable)
- Tous les centres où **"aucun moyen connu de réserver"** => foncé + bouton pour vérifier quand on peut (=url remplie), comme c'est le cas aujourd'hui

**Comment by Maijin** [comment]
Pour un premier jet ça me parait ok,

Perso j'aurai inversé 3 et 4 puisqu'il existe plus de chance de trouver un rendez-vous sur un centre ou l'on ne peux pas verifier la disponibilité que sur un site ou l'on sait qu'il n'y a plus de dose disponible pour le moment. 

Surtout que pour certaines plateformes on ne peux pas verifier si c'est telephone only ce qui risque d'etre le potentiellement + le cas pour ces centres marqué "aucun moyen connu de réserver".

**Comment by fcamblor** [comment]
Petit état des lieux après pas mal d'essais...

J'arrive à distinguer 4 cas de figure (plus ou moins ceux évoqués dans mon précédent post) :
- Les centres sur lesquels on peut prendre rdv en ligne, et qui ont des doses :
<img width="1124" alt="Vaccination_COVID-19_à_Ajaccio_20167" src="https://user-images.githubusercontent.com/603815/115942430-91a77b00-a4aa-11eb-8cb0-e4f3b3b9bb8d.png">
- Les centres sur lesquels on ne peut pas prendre rdv en ligne, car on a détecté que la prise de rdv ne se faisait que par téléphone
<img width="1128" alt="Vaccination_COVID-19_à_Villenave-d_Ornon_33140" src="https://user-images.githubusercontent.com/603815/115942473-be5b9280-a4aa-11eb-8b38-10242b23197e.png">
- Les centres où il est possible de prendre rdv en ligne mais où il ne reste plus de doses dispos
<img width="1125" alt="Vaccination_COVID-19_à_Villenave-d_Ornon_33140" src="https://user-images.githubusercontent.com/603815/115942526-fc58b680-a4aa-11eb-8233-a802733a606c.png">
- Les centres où nous n'avons aucune URL plateforme
<img width="1124" alt="Vaccination_COVID-19_à_Villenave-d_Ornon_33140" src="https://user-images.githubusercontent.com/603815/115942661-9b7dae00-a4ab-11eb-9807-ba4cae4ed2df.png">

Je pense qu'en terme de "priorité", l'ordre défini ci-dessus est le bon.

### Mes questions :
- Je m'interroge sur l'application du **tri par Distance** au sein des 4 sections vues précédemment. Pour moi, on a 3 options :
   - On cloisonne les 4 sections, et on trie par distance à l'intérieur de chacune d'elles : on aura donc les centre où on peut prendre rdv en ligne triés par distance, puis tous les centres où on peut prendre rdv par tel uniquement triés par distance, puis tous les centres sans dose triés par distance, puis tous les centres sans URL triés par distance
   - On applique le tri par distance que sur les sections clair/foncées : on aurait donc les centres où on peut prendre rdv en ligne OU par téléphone qui seraient "mélangés" et triés par distance, puis tous les centres avec soit 0 dose, soit sans URL, mélangés eux-aussi, mais triés par distance
   - On "mélange" les 4 sections et on affiche les centres triés par distance : ça veut dire qu'on peut alterner entre les 4 types de centres, et on aura le tout qui sera entièrement trié par distance

Pour illustrer ces 3 stratégies de tri, j'ai déployé ici un test : https://dev.vitemado.se/73-new-appointment-displays/ dans lequel vous avez un critère permettant de sélectionner la stratégie de tri (ce n'est qu'à but d'illustration pour aider à choisir, l'objectif n'est pas de donner cette possibilité à l'utilisateur)
<img width="1359" alt="Vaccination_COVID-19_à_Villenave-d_Ornon_33140" src="https://user-images.githubusercontent.com/603815/115943726-0a5e0580-a4b2-11eb-8cf6-b8a4e959f97b.png">


- Pour le **tri par date de disponibilité**, c'est un peu différent, car on a des dates de dispo (à priori) uniquement dans le premier cas de figure (prise de rdv possible en ligne et il reste des doses). Dans ce cas de figure, il paraît assez logique de trier "par section" : 
    - Centres avec prise de rdv possible en ligne et avec des doses, triés par date de dispo croissante
    - Centres avec prise de rdv possible uniquement par tel
    - Centres avec prise de rdv en ligne, mais avec 0 doses
    - Centres sans URL
- Est-il possible d'avoir des centre avec `appointment_by_phone_only=true` et avec tantôt `appointment_count == 0` et `appointment_count != 0` ? Si oui, est-il pertinent de faire un distinguo de ces 2 cas de figure ? (afficher en blanc quand on sait qu'il reste des doses sur la plateforme, afficher en gris quand on sait qu'il n'y a plus de doses sur la plateforme)

**Comment by francoisBouchet** [comment]
mho - **tri par distance** (nb : faut dormir, Fréd !!!) : 

_1er stacker par typologie de prise de rendez-vous._
- why-not
- probablement le systeme le plus à meme de fournir la satisfaction utilisateur car on est sûr à 99% qu'il trouvera un créneau et pourra faire sa résa

_2ème : mélanger les modes de prise de rdv (web & tél)._
- why not, j'aime assez... pour les vieux qui ont peur ou galère sur les plateformes de résa, ils seront plus enclins à appeler...
- par contre, on les remet dans un tunnel de "attendre sur le  répondeur"...
- + comme (j'imagine ?) on ne connait pas le stock de doses de ces centres... potentiellement très déceptif et retour sur une boucle déceptive façon santé.fr
--> du coup, si on ne connaît pas le stock de doses des centres phone-only... je pense qu'il faudrait mieux éviter quand même cette solution.

_3ème : melting-pot des 4 types._
NON.
jamais on ne mélangera les résultats sans créneau avec le reste. c'est comme mettre du sucre ou du lait dans son café. c'est interdit ^^!

**Comment by fcamblor** [comment]
Je suis assez d'accord avec toi sur l'option 3 (mélanger les 4 types), ça oblige potentiellement à beaucoup scroller avant de pouvoir prendre un rdv (si on a beaucoup de centres sans doses proche de chez nous)

Ce qui m'ennuie sur l'option 1, c'est que si l'utilisateur a plein de centres éloignés de chez lui sur lesquels il peut prendre rdv via une plateforme, il sera obligé de toutes les scroller avant de s'apercevoir qu'il a un centre potentiellement proche de chez lui mais sur lequel il ne peut prendre rdv que par téléphone.

Pour moi, ton argument sur l'option 2 n'est pas un argument "spécifique à l'option 2"
C'est un questionnement sur le bien fondé de mettre en avant les numéro de tel sur les centres qui sont "phone only" et peut donc s'appliquer sur les 3 stratégies de tri possible.

**Comment by fcamblor** [comment]
Quelques précisions sur des choix ergo que j'ai fait dans la maquette :
- Étant donné que lorsque `appointment_by_phone_only=true`, le champ `prochain_rdv` n'est jamais rempli (j'ai fait le test aujourd'hui à 12:39 sur tous les départements), j'ai préféré mettre un titre "Réservation tél uniquement" en guise de titre car nous n'aurons jamais de date/heure de premier rdv dans ce cas de figure
- Je me suis aperçu qu'il était possible d'avoir des centres avec une URL plateforme + des doses disponibles, mais avec un `prochain_rdv` qui soit `null` (j'ai remonté le soucis à l'équipe en charge de Maiia car nous n'avons qu'un seul centre sur 1920 dans ce cas de figure)

**Comment by francoisBouchet** [comment]
> Ce qui m'ennuie sur l'option 1, c'est que si l'utilisateur a plein de centres éloignés de chez lui sur lesquels il peut prendre rdv via une plateforme, il sera obligé de toutes les scroller avant de s'apercevoir qu'il a un centre potentiellement proche de chez lui mais sur lequel il ne peut prendre rdv que par téléphone.

normalement ton switch "au plus proche" est justement là pour répondre à cette problématique. 

donc sur la view "à date de proximité", éventuellement si la personne provenait précédemment de la vue "au plus proche", tu peux conserver en session sa "last proximity", et lui ordonner les créneaux les plus tôts, et dedans du plus proche au plus éloigné kilométriquement... mais sinon il faut respecter ce choix initial de prioriser l'ordre par date.

**Comment by francoisBouchet** [comment]
> 
> 
> Je suis assez d'accord avec toi sur l'option 3 (mélanger les 4 types), ça oblige potentiellement à beaucoup scroller avant de pouvoir prendre un rdv (si on a beaucoup de centres sans doses proche de chez nous)
> 
> Ce qui m'ennuie sur l'option 1, c'est que si l'utilisateur a plein de centres éloignés de chez lui sur lesquels il peut prendre rdv via une plateforme, il sera obligé de toutes les scroller avant de s'apercevoir qu'il a un centre potentiellement proche de chez lui mais sur lequel il ne peut prendre rdv que par téléphone.
> 

oui, je trouve aussi qu'en plus on est sur un écran qui priorise la distance avant le reste, donc plutôt partant pour option 2. in fine.

> Pour moi, ton argument sur l'option 2 n'est pas un argument "spécifique à l'option 2"
> C'est un questionnement sur le bien fondé de mettre en avant les numéro de tel sur les centres qui sont "phone only" et peut donc s'appliquer sur les 3 stratégies de tri possible.

oui oui, pas forcément spécifique, mais la card en question va mettre en exergue le numéro de tél... donc cette exergue plus cette priorisation dans l'ordre d'affichage... je ne l'octroierai qu'aux lieux qui sont le plus susceptibles d'apporter une satisfaction utilisateur sur la résa... mais je ne sais pas si on a les données suffisantes pour le savoir...

**Comment by fcamblor** [comment]
fixé via #117
