### ISSUE TITLE
index : retirer les balises <a href=""> vides sur chacun des logos

### ISSUE THREAD

**Issue by francoisBouchet** [CovidTrackerFr/vitemadose-front#75]
on a des liens vides (et donc inutiles) sur chacun des logos des plateformes de santé listés sur la homepage.

--> à retirer ! (les liens vides, pas les logos ;P)

merci.

**Comment by fcamblor** [comment]
je cloture : #80 a rajouté des liens vers les plateformes

**Comment by fcamblor** [comment]
@francoisBouchet j'y repense ... niveau SEO, ces liens sortant pourraient-ils avoir un effet négatif ? (j'ai mergé sans réfléchir hier)

**Comment by francoisBouchet** [comment]
SEO : c'est généralement pas très bon de faire trop de liens sortants dès la homepage (même si ici ils ont "dans la thématique"), et comme on n'a pas bcoup de liens sur cette page...

UX : le but est d'éviter à l'utilisateur de galérer dans les moteurs de recherche des plateformes... et de lui simplifier la vie via notre site. --> pointer dès la homepage vers les plateformes démultiplient autant de fois qu'il y a de liens les chances de le renvoyer vers la galère du parcours vaccinal habituel.

Tout notre site est un hub dispatch vers les plateformes. en homepage on peut se contenter de les afficher, pour de la simple "réassurance" visuelle. et c'est bien suffisant.

c'est pour ces raisons que j'avais créé ce ticket... :-/
