### ISSUE TITLE
 Ordoclic - Pharmacie sans doses affichées 

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose-front#81]
https://app.ordoclic.fr/app/pharmacie/pharmacie-de-la-pyramide-macon.

![image](https://user-images.githubusercontent.com/1408600/115065966-26c8d380-9eef-11eb-91ad-01f745075cb6.png)

![image](https://user-images.githubusercontent.com/1408600/115066048-452ecf00-9eef-11eb-8515-39db52f7a616.png)

![image](https://user-images.githubusercontent.com/1408600/115086764-2e977080-9f0d-11eb-9d72-df46953f5969.png)

Per @gaelbenoit "En fait je ne peux pas toujours discriminer les centres au moment de l'iterator. Pour mapharma par exemple j'ai un endpoint qui me donne la liste des pharmacies et en même temps s'il y a des doses dispos. Pour ordoclic j'ai un endpoint qui me renvoie la liste des pharmacies, et après pour chaque pharmacie je vérifie la dispo au moment de fetch_slots. Donc quand je yield sur l'iterator je ne sais pas s'il y a de la dispo

bien entendu je peux vérifier les slots au moment de l'iterator mais ce serait encore plus simple de filtrer au niveau du front et de ne pas afficher les pharma à 0"

**Comment by fcamblor** [comment]
@Maijin pourquoi ne pas mettre cette règle coté back (si dose=0 => centre à mettre dans `centres_indisponibles`) plutôt que d'avoir à l'implémenter dans tous les fronts (web, ios, android) ?

**Comment by Maijin** [comment]
@fcamblor voir remarque de @gaelbenoit^^^

**Comment by gaelbenoit** [comment]
on pourrait par exemple faire 3 catégories au niveau back: centres avec dispo, centres sans dispo, centres sans dispo mais pour lesquels on sait qu'ils prennent des rdv par téléphone (ok je sais c'est pas vraiment possible partout) et ne pas afficher les centres indisponibles. Actuellement les centres à 0 sont classés dans `centres_indisponibles`

**Comment by fcamblor** [comment]
lié à (voire duplicate de) #73 , non ?

**Comment by fcamblor** [comment]
Je ferme l'issue car #73 a été mergée hier et je pense qu'elle fix le problème (testable ici : https://dev.vitemado.se/dev/)

N'hésitez pas à réopen si ce n'est pas le cas :)
