### ISSUE TITLE
Compatibilité IE 11 ?

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#85]
Nous avons eu des retours comme quoi le site ne fonctionnait pas sous IE 11

Il faudrait voir si c'est un problème de fond (par exemple, lié à lit-element) ou si ce n'est que quelques appels à des fonctions JS non supportées, qui posent problème.

**Comment by nhumblot** [comment]
Premier test rapide effectué sur IE11:

Je constate le mauvais fonctionnement mais aucune erreur affichée dans la console développeur.

![image](https://user-images.githubusercontent.com/15015617/115280969-caf98700-a148-11eb-9104-9088666cb4e6.png)

**Comment by nhumblot** [comment]
ViteJs provide a legacy plugin, which supports IE11

https://github.com/nhumblot/vitemadose-front/commit/dcea309f757eeb87d1d24041a167c6d5e4875675

With this commit, a `vendor-legacy` is generated but when launching it I'm facing some errors. I will continue the investigation.

**Comment by nhumblot** [comment]
À noter, un `npm run dev` ne semble pas fonctionner correctement, aucun style est lancé dans cette configuration. En effectuant un `npm run build` et en servant le dist sur un serveur http, je suis en mesure de reproduire un comportement équivalement. Cette différence est constatée uniquement sous IE11, pas de soucis avec un essai sur Edge.

**Comment by fcamblor** [comment]
tu peux aller éditer le `build.sourcemap` dans le `vite.config.ts` pour générer les sourcemaps durant le build (ça peut aider pour le debug)

**Comment by bilelz** [comment]
> À noter, un `npm run dev` ne semble pas fonctionner correctement, aucun style est lancé dans cette configuration. En effectuant un `npm run build` et en servant le dist sur un serveur http, je suis en mesure de reproduire un comportement équivalement. Cette différence est constatée uniquement sous IE11, pas de soucis avec un essai sur Edge.

Hello, 
Edge legacy (<v79) ou Edge chromium? J'ai testé sur Edge legacy sans succès

**Comment by nhumblot** [comment]
> Hello,
> Edge legacy (<v79) ou Edge chromium? J'ai testé sur Edge legacy sans succès

J'ai un edge chromium. Pas testé sur edge legacy.

**Comment by bilelz** [comment]
OK. 
Pour prévenir les utilisateurs que leur navigateur est obsolète, j'ai poussé une PR #120 

Sur ie11 et chrome legacy ça donne ça:
![image](https://user-images.githubusercontent.com/1426314/116082864-2fae6780-a69c-11eb-886c-0ff4c5452c52.png)

(mis à jour avec les couleurs du formulaire)

**Comment by nhumblot** [comment]
https://github.com/CovidTrackerFr/vitemadose-front/pull/215#issuecomment-844938020

La compatibilité IE11 ne semble plus d'actualité. @bilelz a déjà ajouté un bandeau indiquant que ce navigateur est obsolète. Je clôture l'issue. Si quelqu'un n'est pas d'accord, qu'il n'hésite pas à la ré-ouvrir.
