### ISSUE TITLE
ANALYTICS (un peu urgent) : tagging JS à implémenter sur le front-end

### ISSUE THREAD

**Issue by francoisBouchet** [CovidTrackerFr/vitemadose-front#86]
JBlePrado nous a fourni un brief / plan de tagging très détaillé, pour optimiser au mieux les stats d'utilisations de Vite Ma Dose.

il est accessible à cette URL : 
https://docs.google.com/spreadsheets/d/1dhANE4U_Xlo_U_NpCQC3doP7emkoQ3rW0iQibdwJqB0/edit#gid=39658297

il y a une colonne "DEV-SPECS" dédiée aux dév front-end, avec des functions JS à lancer lors de chargement de "pages", ou d'interactions utilisateurs.

Est-ce complexe à mettre en place ? 
Est-il possible d'envisager une MEP là-dessus avant le passage TV de Guillaume ? ou trop risqué ?

NB: JB n'a pas forcément vu le nouveau moteur de recherche... je l'ai briefé dessus, mais pour l'instant son brief concerne l'existant en PROD.

merci !

**Comment by fcamblor** [comment]
Done
