### ISSUE TITLE
bug rsync deployment with CI 

### ISSUE THREAD

**Issue by yannis-mlgrn** [CovidTrackerFr/vitemadose-front#89]
bonjour,
J'ai remarqué que quand on fait une PR de notre fork à la repo original, Le CI nous notifie une erreur au niveau du "rsync deployment" et donc ne valide pas notre PR. Par contre si on fait une autre directement sur la repository original clonée en local le CI ne notifie aucune erreur. Ce bug serai du à un problème de droit avec notre fork.

**Comment by fcamblor** [comment]
Oui, c'est un problème de sécurité : l'action github s'exécute en utilisant les variables définies au niveau du "repository d'origine" d'où vient la PR.

Étant donné que tu n'as pas défini de variables pour le déploiement, le build se plante (et c'est tant mieux, car si ce n'était pas le cas, rien ne t'empêcherait de faire une PR qui fait, dans les github actions, un `echo` des variables configurées sur notre repository, pour récupérer leurs valeurs)

Il faut surtout que j'empêche la github action de se trigger si la branche concernée n'est pas une branche locale (je ne suis pas sûr que cela soit possible de le faire ... au pire je désactiverait cette feature sur les PR)

**Comment by Benvii** [comment]
Problème fixé sur ma PR, voir mon commentaire : https://github.com/CovidTrackerFr/vitemadose-front/pull/103#issuecomment-823618527 

Il reste à faire un test par quelqu'un qui peut push sur le base repository ( *CovidTrackerFr/vitemadose-front* ), peut-être @fcamblor ?
