### ISSUE TITLE
[Doc] Recommander l'usage de "npm ci" et non "npm install"

### ISSUE THREAD

**Issue by Benvii** [CovidTrackerFr/vitemadose-front#92]
Bonjour,
Afin d'éviter des mises à jours intempestives de librairies (et donc des modification du package-lock.json) ainsi que les instabilités que cela entraîne il est recommandé de ne pas utiliser `npm install` (qui prend des libertés et MAJ des libs) mais d'utiliser `npm ci`. Ceci y compris dans la doc des développeurs, ça leur évitera de push un `package-lock.json` modifié, s'assurer qu'ils ont bien le même environnement qu'une fois déployé et donc éviter des bugs en prod qui n'auraient pas étaient vu en dev.

Retenir qu'en général `npm install` n'est utilisé que pour l'ajout / maj de librairies et utiliser `npm ci` dans tous les autres cas.

Voir ce stackoverflow pour plus de détail : https://stackoverflow.com/a/53325242 

Je vous push un correctif de la doc dev. 
Je vois que les conf/recettes de déploiement utilisé déjà bien le `npm ci` :+1:

**Comment by fcamblor** [comment]
Thanks 👍
