### ISSUE TITLE
Validation de l'input "localisation" avec la touche entrée

### ISSUE THREAD

**Issue by FKSI** [CovidTrackerFr/vitemadose-front#97]
Autoriser la validation de la saisie de la localisation avec la touche entrée.

<img width="846" alt="Capture d’écran 2021-04-20 à 11 09 37" src="https://user-images.githubusercontent.com/2216173/115370097-0471d700-a1c9-11eb-9796-e672bff17555.png">

**Comment by fcamblor** [comment]
Hello !

Je ne comprends pas le fonctionnement qui serait attendu : vu qu'on ne pré-selectionne aucun des choix (et qu'il est impossible pour le moment de naviguer au clavier parmi ces derniers), pourrais-tu détailler davantage ce que tu attendrais ?

Car pour moi, si on veut pouvoir faire une navigation au clavier il faut :
- Pouvoir se déplacer parmi les choix possibles via les touches ⬆️ ⬇️ tout en conservant le focus dans l'input
- Lorsqu'un choix est sélectionné via cette navigation, permettre de valider son choix via la touche entrée

**Comment by FKSI** [comment]
Hello :) 

Oh bien vu pour les multiples cas, j'ai saisi directement mon CP du coup en tant que dev mon réflex a été de taper sur Entrée.  C'est peut-être un nice-to-have alors :).

**Comment by Noezor** [comment]
Et pareil pour les flêches pour pouvoir naviguer la liste :B

**Comment by bilelz** [comment]
> Hello !
> 
> Je ne comprends pas le fonctionnement qui serait attendu : vu qu'on ne pré-selectionne aucun des choix (et qu'il est impossible pour le moment de naviguer au clavier parmi ces derniers), pourrais-tu détailler davantage ce que tu attendrais ?
> 
> Car pour moi, si on veut pouvoir faire une navigation au clavier il faut :
> 
> * Pouvoir se déplacer parmi les choix possibles via les touches ⬆️ ⬇️ tout en conservant le focus dans l'input
> * Lorsqu'un choix est sélectionné via cette navigation, permettre de valider son choix via la touche entrée

Hello,

Le champ de recherche de github a quasiment ce fonctionnement
- présélection de la première option
- navigation avec les touches ⬆️ ⬇️ 
- si l'utilisateur appuie sur `entrée`, l'utilisateur est redirigé vers l'option sélectionnée
- Et pour encore plus d'accessibilité, faudrait gérer l'attribut role:
   - https://developer.mozilla.org/fr/docs/Web/Accessibility/ARIA/Roles/listbox_role

Je viens de `fork` le projet, j'essaierai de faire une PR dans ce sens...

**Comment by fcamblor** [comment]
Je viens de merger la PR #108 de @bilelz  qui traite ce point (et bien d'autres !) 💪  => je ferme l'issue
